import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        slug: '/category/api-reference',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
  ],
};

export default sidebars;
