swagger: "2.0"
info:
  title: help_center/v1/api.proto
  version: version not set
tags:
  - name: HelpCenter
  - name: ArticleOperations
consumes:
  - application/json
produces:
  - application/json
paths:
  /helpcenter.v1.ArticleOperations/ArticleHiddenToggle:
    post:
      summary: Toggles if an article should be filtered from search or not
      operationId: ArticleOperations_ArticleHiddenToggle
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ArticleHiddenToggleRequest'
      tags:
        - ArticleOperations
  /helpcenter.v1.HelpCenter/DeleteArticle:
    post:
      summary: Soft delete an article from vstore to filter from search
      operationId: HelpCenter_DeleteArticle
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeleteArticleRequest'
      tags:
        - HelpCenter
  /helpcenter.v1.HelpCenter/DirectIndexArticle:
    post:
      summary: Directly index an article into vstore to be searched by supplying the article directly
      operationId: HelpCenter_DirectIndexArticle
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DirectIndexArticleRequest'
      tags:
        - HelpCenter
  /helpcenter.v1.HelpCenter/IndexArticle:
    post:
      summary: Index an article from into vstore to be searched
      operationId: HelpCenter_IndexArticle
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1IndexArticleRequest'
      tags:
        - HelpCenter
  /helpcenter.v1.HelpCenter/SearchArticle:
    post:
      summary: Search Help Center's article index for relevant articles based on SearchRequest and return an array of article stubs in SearchResponse
      operationId: HelpCenter_SearchArticle
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SearchArticleResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SearchArticleRequest'
      tags:
        - HelpCenter
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Article:
    type: object
    properties:
      articleId:
        type: string
        title: External article ID used by the third party to idenfity the article
      locale:
        type: string
        title: 'Localization type: "en-us"'
      origin:
        $ref: '#/definitions/v1Origins'
        title: Origin of article
      url:
        type: string
        title: |-
          URL to view the full article
          Example: https://somesite.com/help/my-page
      title:
        type: string
        title: Title of the article
      content:
        type: string
        title: |-
          The content or a snippet of the article to be indexed
          HTML will be stripped, special characters respected
          The start of the content will be displayed first based on available space
      tags:
        type: array
        items:
          type: string
        title: |-
          Tags associated to the article to assist search
          Example: sales, automation, api
      sourceModified:
        type: string
        format: date-time
        title: When the article was last edited
      voteCount:
        type: string
        format: int64
        title: How many votes an article has on it
      voteSum:
        type: string
        format: int64
        title: What the total sum of the votes is (positive - negative)
      promoted:
        type: boolean
        title: If the article is promoted or not
      replyCount:
        type: string
        format: int64
        title: How many replies the article has
      viewCount:
        type: string
        format: int64
        title: How many views the article has
      solved:
        type: boolean
        title: If the article is solved or not
      answerCount:
        type: string
        format: int64
        title: How many answers the article has
      thumnailLinkUrl:
        type: string
        title: "A link to a thumbnail image for the article\nThe image must be hosted at a publicly accessible location. \nExample: https://somesite.com/help/assets/image123.gif"
  v1ArticleHiddenToggleRequest:
    type: object
    properties:
      articleId:
        type: string
        title: External article ID used by the third party to idenfity the article
      locale:
        type: string
        title: Localization type
      origin:
        $ref: '#/definitions/v1Origins'
        title: Origin of article
    title: Request to toggle the hidden flag on an article to hide/show it in search
  v1ArticleStub:
    type: object
    properties:
      title:
        type: string
        title: Title of article
      body:
        type: string
        title: Article's stubbed body
      origin:
        type: string
        title: Origin of article (Community, Academy, Resource Center, etc.)
      link:
        type: string
        title: Link to full article
      thumbnail:
        type: string
        title: Link to the associated thumbnail
    title: Article stub returned to display on search query
  v1DeleteArticleRequest:
    type: object
    properties:
      articleId:
        type: string
        title: External article ID used by the third party to idenfity the article
      locale:
        type: string
        title: Localization type
      origin:
        $ref: '#/definitions/v1Origins'
        title: Origin of article
    title: Request to delete an article from Help Center's search
  v1DirectIndexArticleRequest:
    type: object
    properties:
      article:
        $ref: '#/definitions/v1Article'
    title: Request to directly index an article into Help Center's search
  v1FilterParams:
    type: object
    properties:
      origins:
        type: array
        items:
          $ref: '#/definitions/v1Origins'
  v1IndexArticleRequest:
    type: object
    properties:
      articleId:
        type: string
        title: External article ID used by the third party to idenfity the article
      locale:
        type: string
        title: Localization type
      origin:
        $ref: '#/definitions/v1Origins'
        title: Origin of article
    title: Request to index an article into Help Center's search
  v1Origins:
    type: string
    enum:
      - ORIGINS_UNSPECIFIED
      - ORIGINS_COMMUNITY_WP
      - ORIGINS_ACADEMY_WP
      - ORIGINS_RESOURCE_CENTER_ZENDESK
      - ORIGINS_VIDEO_WP
      - ORIGINS_BP_MEMBERS_WP
      - ORIGINS_ACADEMY_LESSON_WP
      - ORIGINS_BP_GROUP_WP
      - ORIGINS_PODCASTS_WP
      - ORIGINS_OPEN_API
      - ORIGINS_COMMUNITY_POST_ZENDESK
    default: ORIGINS_UNSPECIFIED
    title: All supported origins of articles to index from
  v1PagedRequestOptions:
    type: object
    properties:
      cursor:
        type: string
        title: cursor can be passed to retrieve the next page of results keyed by the cursor
      pageSize:
        type: string
        format: int64
        title: page_size specifies the number of items to return in the next page
  v1PagedResponseMetadata:
    type: object
    properties:
      nextCursor:
        type: string
        title: A cursor that can be provided to retrieve the next page of results
      hasMore:
        type: boolean
        title: Whether or not more results exist
      totalResults:
        type: string
        format: int64
        title: The total number of results. This is not supported on all paged apis and will be 0 if it is not supported
  v1SearchArticleRequest:
    type: object
    properties:
      searchTerm:
        type: string
        title: Current input search value
      locale:
        type: string
        title: Localization type
      filters:
        $ref: '#/definitions/v1FilterParams'
        title: This takes in filters params that excludes the origins from the search results
      pagingOptions:
        $ref: '#/definitions/v1PagedRequestOptions'
    title: Request for Help Center's search
  v1SearchArticleResponse:
    type: object
    properties:
      articles:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ArticleStub'
        title: List of relevant article stubs
      pagingMetadata:
        $ref: '#/definitions/v1PagedResponseMetadata'
    title: Response for Help Center's search
