swagger: "2.0"
info:
  title: google_analytics/v1/api.proto
  version: version not set
tags:
  - name: Views
  - name: Records
consumes:
  - application/json
produces:
  - application/json
paths:
  /googleanalytics.v1.Records/CollectRecords:
    post:
      summary: CollectRecords launches the collection of GA records from a period of time
      operationId: Records_CollectRecords
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CollectRecordsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CollectRecordsRequest'
      tags:
        - Records
  /googleanalytics.v1.Views/DeleteView:
    post:
      summary: DeleteView deletes a view
      operationId: Views_DeleteView
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DeleteViewResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeleteViewRequest'
      tags:
        - Views
  /googleanalytics.v1.Views/GetAvailableViews:
    post:
      summary: GetAvailableViews returns a collection of GA views that can be chosen from to set a View for querying GA
      operationId: Views_GetAvailableViews
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAvailableGAViewsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAvailableGAViewsRequest'
      tags:
        - Views
  /googleanalytics.v1.Views/GetView:
    post:
      summary: GetView returns the currently set GA view for a business
      operationId: Views_GetView
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetViewResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetViewRequest'
      tags:
        - Views
  /googleanalytics.v1.Views/SetView:
    post:
      summary: SetView sets a business's GA view for querying
      operationId: Views_SetView
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SetViewResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetViewRequest'
      tags:
        - Views
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CollectRecordsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The Partner ID of the account to collect records
      businessId:
        type: string
        title: The Business ID of the account to collect records
      startDate:
        type: string
        format: date-time
        title: The date to start collecting records (inclusive)
      endDate:
        type: string
        format: date-time
        title: the date to end collecting records (inclusive)
  v1CollectRecordsResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The succuess/fail response
  v1DeleteViewRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the view is associated with
      businessId:
        type: string
        title: The business ID the view is associated with (aka the account group ID)
    title: The request sent to flag a view as deleted
  v1DeleteViewResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The success/fail response when deleting a view
  v1GAView:
    type: object
    properties:
      gaAccountName:
        type: string
        title: The Google Analytics account name
      gaAccountId:
        type: string
        title: The Google Analytics account ID
      gaWebPropertyName:
        type: string
        title: The Google Analytics web property name
      gaWebPropertyId:
        type: string
        title: The Google Analytics web property ID
      gaViewName:
        type: string
        title: The Google Analytics view name
      gaViewId:
        type: string
        title: The Google Analytics view ID
  v1GetAvailableGAViewsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID for the account making the request
      businessId:
        type: string
        title: The business ID for the account making the request (aka the account group ID)
      cursor:
        type: string
        title: An optional cursor to be provided when fetching additional pages of results beyond the first
    title: "Request that will query Google for the views available to the GA account \nassociated with the Partner ID and Business ID. \nThis will only be called after a user has granted authorization to connect\nTheir GA account"
  v1GetAvailableGAViewsResponse:
    type: object
    properties:
      views:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1GAView'
        title: GAView object to which this user has access
      nextCursor:
        type: string
        title: A cursor for the next page of results, will be empty if no subsequent pages
    title: List of views available to the connected Google Analytics account
  v1GetViewRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the view is associated with
      businessId:
        type: string
        title: The business ID the view is associated with (aka the account group ID)
    title: Get the current view connected an an account
  v1GetViewResponse:
    type: object
    properties:
      view:
        $ref: '#/definitions/v1View'
        title: The view struct returned
  v1SetViewRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the view is associated with
      businessId:
        type: string
        title: The business ID the view is associated with (aka the account group ID)
      gaAccountId:
        type: string
        title: The Google Analytics account ID the stored view will be connected to
      gaPropertyId:
        type: string
        title: The Google Analytics property ID the stored view will be connected to
      gaViewId:
        type: string
        title: The Google Analytics view ID the stored view with be connected to
    title: The request sent to store a view to start querying data
  v1SetViewResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The success/fail response when setting a view
  v1View:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the view is associated with
      businessId:
        type: string
        title: The business ID the view is associated with (aka the account group ID)
      googleUserId:
        type: string
        title: The Google User ID associated with the view.  This is how we link the view to an Oauth Token
      gaAccountName:
        type: string
        title: The Google Analytics Account name
      gaAccountId:
        type: string
        title: The Google Analytics account ID
      gaWebPropertyName:
        type: string
        title: The Google Analytics Web Property Name
      gaWebPropertyId:
        type: string
        title: The Google Analytics Web Property ID
      gaViewId:
        type: string
        title: The Google Analytics view ID
      gaViewName:
        type: string
        title: The Google Analytics view name
      gaUserName:
        type: string
        title: The Username associated with the Google Analytics account
      subjectFirstName:
        type: string
        title: The user's first name
      subjectLastName:
        type: string
        title: the user's last name
      created:
        type: string
        format: date-time
        title: The time the view was first created
      updated:
        type: string
        format: date-time
        title: The last time a view was updated
      isBroken:
        type: boolean
        title: A flag to show whether or not the view is working properly
      initialCollectionRunning:
        type: boolean
        title: A flag to show whether or not the initial collection is still running
