swagger: "2.0"
info:
  title: local_marketing_index/v1/local_marketing_index.proto
  version: version not set
tags:
  - name: LocalMarketingIndex
  - name: ThirdPartyGradesService
consumes:
  - application/json
produces:
  - application/json
paths:
  /localmarketingindex.v1.LocalMarketingIndex/GetGradeMulti:
    post:
      summary: Get a set of lmi category grades for a set of accounts
      operationId: LocalMarketingIndex_GetGradeMulti
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetGradeMultiResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetGradeMultiRequest'
      tags:
        - LocalMarketingIndex
  /localmarketingindex.v1.LocalMarketingIndex/GetListingAccuracy:
    post:
      summary: Get the listing accuracy data for an account
      operationId: LocalMarketingIndex_GetListingAccuracy
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetListingAccuracyResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetListingAccuracyRequest'
      tags:
        - LocalMarketingIndex
  /localmarketingindex.v1.LocalMarketingIndex/GetListingPresence:
    post:
      summary: Get the listing presence data for an account
      operationId: LocalMarketingIndex_GetListingPresence
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetListingPresenceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetListingPresenceRequest'
      tags:
        - LocalMarketingIndex
  /localmarketingindex.v1.ThirdPartyGradesService/CreateThirdPartyGrade:
    post:
      summary: Create a grade record for a date
      operationId: ThirdPartyGradesService_CreateThirdPartyGrade
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateThirdPartyGradeRequest'
      tags:
        - ThirdPartyGradesService
  /localmarketingindex.v1.ThirdPartyGradesService/GetThirdPartyGradesForDate:
    post:
      summary: Get the grades for a date
      operationId: ThirdPartyGradesService_GetThirdPartyGradesForDate
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetThirdPartyGradesForDateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetThirdPartyGradesForDateRequest'
      tags:
        - ThirdPartyGradesService
  /v1/grades/create:
    post:
      summary: Create a lmi category grade for an account
      operationId: LocalMarketingIndex_CreateGrade
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateGradeResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateGradeRequest'
      tags:
        - LocalMarketingIndex
  /v1/grades/get:
    post:
      summary: Get a lmi category grade for an account
      operationId: LocalMarketingIndex_GetGrade
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetGradeResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetGradeRequest'
      tags:
        - LocalMarketingIndex
  /v1/grades/regional/get:
    post:
      summary: Get regional grades for an account
      operationId: LocalMarketingIndex_GetRegionalGrades
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetRegionalGradesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetRegionalGradesRequest'
      tags:
        - LocalMarketingIndex
  /v1/industry-stats/get:
    post:
      summary: Get the industry stats based on taxonomy
      operationId: LocalMarketingIndex_GetIndustryStats
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetIndustryStatsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetIndustryStatsRequest'
      tags:
        - LocalMarketingIndex
  /v1/scores/get:
    post:
      summary: Get a lmi category score for an account
      operationId: LocalMarketingIndex_GetScore
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetScoreResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetScoreRequest'
      tags:
        - LocalMarketingIndex
  /v1/scores/historical/get:
    post:
      summary: Get the historical listing score for an account
      operationId: LocalMarketingIndex_GetHistoricalScoreData
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetHistoricalScoreDataResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetHistoricalScoreDataRequest'
      tags:
        - LocalMarketingIndex
definitions:
  GetGradeMultiResponseGradeContainer:
    type: object
    properties:
      grade:
        $ref: '#/definitions/v1Grade'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Category:
    type: string
    enum:
      - LISTINGS
      - REPUTATION
      - SOCIAL
      - WEBSITE
      - SEO
      - ADVERTISING
      - CONTENT_AND_EXPERIENCE
    default: LISTINGS
  v1CreateGradeRequest:
    type: object
    properties:
      accountGroupId:
        type: string
      category:
        $ref: '#/definitions/v1Category'
      letterGrade:
        $ref: '#/definitions/v1LetterGrade'
      source:
        type: string
  v1CreateGradeResponse:
    type: object
    properties:
      grade:
        $ref: '#/definitions/v1Grade'
  v1CreateThirdPartyGradeRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner id for the exec report
      businessId:
        type: string
        title: Business id is the vendasta id for this business
      grade:
        type: string
        title: Letter grade for the category
      gradeDate:
        type: string
        format: date-time
        title: Date that this grade belongs to
      gradeSection:
        $ref: '#/definitions/v1ThirdPartyCategory'
        title: Category that the grade belongs to
  v1GetGradeMultiRequest:
    type: object
    properties:
      accountGroupIds:
        type: array
        items:
          type: string
      category:
        $ref: '#/definitions/v1Category'
  v1GetGradeMultiResponse:
    type: object
    properties:
      grades:
        type: array
        items:
          type: object
          $ref: '#/definitions/GetGradeMultiResponseGradeContainer'
  v1GetGradeRequest:
    type: object
    properties:
      accountGroupId:
        type: string
      category:
        $ref: '#/definitions/v1Category'
    title: |-
      *******************
      Requests
      *******************
  v1GetGradeResponse:
    type: object
    properties:
      grade:
        $ref: '#/definitions/v1Grade'
    title: |-
      *******************
      Responses
      *******************
  v1GetHistoricalScoreDataRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        title: The unique identifier for the account group
      category:
        $ref: '#/definitions/v1Category'
        title: The unique identifier for the category
    title: A request for getting the historical score for an account
  v1GetHistoricalScoreDataResponse:
    type: object
    properties:
      historicalScoreData:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1HistoricalScoreDataPoint'
        description: The historical listing score of the account group.
    title: A response containing the historical listing score for an account
  v1GetIndustryStatsRequest:
    type: object
    properties:
      category:
        $ref: '#/definitions/v1Category'
        title: The unique identifier for the category
      taxonomyId:
        type: string
        description: The unique identifier of the taxonomy.
      country:
        type: string
        description: The unique identifier of the country.
      state:
        type: string
        description: The unique identifier of the state.
      city:
        type: string
        description: The unique identifier of the city.
    title: A request for getting the industry stats for a taxonomy
  v1GetIndustryStatsResponse:
    type: object
    properties:
      world:
        $ref: '#/definitions/v1IndustryStats'
        title: The industry stats based on world
      country:
        $ref: '#/definitions/v1IndustryStats'
        title: The industry stats based on country
      state:
        $ref: '#/definitions/v1IndustryStats'
        title: The industry stats based on state
      city:
        $ref: '#/definitions/v1IndustryStats'
        title: The industry stats based on city
    title: A response containing the industry stats for a taxonomy
  v1GetListingAccuracyRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        description: The unique identifier of the account group.
      sourceIds:
        type: array
        items:
          type: string
          format: int64
        title: Source Ids to base the score off of
    title: A request for getting the listing accuray data for an account
  v1GetListingAccuracyResponse:
    type: object
    properties:
      listingAccuracy:
        type: number
        format: float
        title: The actual listing accuracy for that account
      worldAverage:
        type: number
        format: float
        title: The average listing accuracy for all accounts under same taxonomy category
      countryAverage:
        type: number
        format: float
        title: The average listing accuracy for all accounts under same taxonomy category and same country
      stateAverage:
        type: number
        format: float
        title: The average listing accuracy for all accounts under same taxonomy category and same state
      cityAverage:
        type: number
        format: float
        title: The average listing accuracy for all accounts under same taxonomy category and same city
    title: A response containing the listing accuracy values for an account
  v1GetListingPresenceRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        description: The unique identifier of the account group.
      sourceIds:
        type: array
        items:
          type: string
          format: int64
        title: Source Ids to base the score off of
    title: A request for getting the listing presence data for an account
  v1GetListingPresenceResponse:
    type: object
    properties:
      listingCount:
        type: string
        format: int64
        title: The actual listing count for that account
      worldAverage:
        type: number
        format: float
        title: The average listing count for all accounts under same taxonomy category
      countryAverage:
        type: number
        format: float
        title: The average listing count for all accounts under same taxonomy category and same country
      stateAverage:
        type: number
        format: float
        title: The average listing count for all accounts under same taxonomy category and same state
      cityAverage:
        type: number
        format: float
        title: The average listing count for all accounts under same taxonomy category and same city
    title: A response containing the listing presence values for an account
  v1GetRegionalGradesRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        title: The unique identifier for the account group
      category:
        $ref: '#/definitions/v1Category'
        title: The unique identifier for the category
      sourceIds:
        type: array
        items:
          type: string
          format: int64
        title: Source Ids to base the grade off of
    title: A request for getting the regional grades for an account
  v1GetRegionalGradesResponse:
    type: object
    properties:
      country:
        $ref: '#/definitions/v1LetterGrade'
        title: The letter grade based on the country
      state:
        $ref: '#/definitions/v1LetterGrade'
        title: The letter grade based on the state
      city:
        $ref: '#/definitions/v1LetterGrade'
        title: The letter grade based on the city
      world:
        $ref: '#/definitions/v1LetterGrade'
        title: The letter grade based on the world
      updated:
        type: string
        format: date-time
        title: The last updated timestamp for the account
    title: A response containing the regional grades for an account
  v1GetScoreRequest:
    type: object
    properties:
      accountGroupId:
        type: string
      category:
        $ref: '#/definitions/v1Category'
      sourceIds:
        type: array
        items:
          type: string
          format: int64
        title: Source Ids to base the score off of
  v1GetScoreResponse:
    type: object
    properties:
      score:
        type: string
        format: int64
  v1GetThirdPartyGradesForDateRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: partner id that we want the grades for
      businessId:
        type: string
        title: business id we want the grades for
      reportStartDate:
        type: string
        format: date-time
        title: start date of the report
      reportEndDate:
        type: string
        format: date-time
        title: end date of the report
  v1GetThirdPartyGradesForDateResponse:
    type: object
    properties:
      grades:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ThirdPartyGrade'
  v1Grade:
    type: object
    properties:
      accountGroupId:
        type: string
      letterGrade:
        $ref: '#/definitions/v1LetterGrade'
      category:
        $ref: '#/definitions/v1Category'
      updated:
        type: string
        format: date-time
      source:
        type: string
  v1HistoricalScoreDataPoint:
    type: object
    properties:
      score:
        type: string
        format: int64
        title: The listing score
      timestamp:
        type: string
        format: date-time
        title: The timestamp for listing score
    title: A model definition for historical score data and required time format
  v1IndustryStats:
    type: object
    properties:
      average:
        type: number
        format: float
      percentiles:
        $ref: '#/definitions/v1Percentiles'
    title: A model definition for industry stats average and relevant percentiles
  v1LetterGrade:
    type: string
    enum:
      - A
      - B
      - C
      - D
      - F
      - NO_GRADE
    default: A
  v1Percentiles:
    type: object
    properties:
      ninetyFifth:
        type: number
        format: float
      eightieth:
        type: number
        format: float
      fiftieth:
        type: number
        format: float
      twentieth:
        type: number
        format: float
      tenth:
        type: number
        format: float
      ninetieth:
        type: number
        format: float
      seventyFifth:
        type: number
        format: float
      fortieth:
        type: number
        format: float
      thirtieth:
        type: number
        format: float
    title: Relevant percentiles for computing letter grades and industry stats
  v1ThirdPartyCategory:
    type: string
    enum:
      - THIRD_PARTY_CATEGORY_SECTION_UNSPECIFIED
      - THIRD_PARTY_CATEGORY_SECTION_LISTING
      - THIRD_PARTY_CATEGORY_SECTION_REVIEWS
      - THIRD_PARTY_CATEGORY_SECTION_WEBSITE
      - THIRD_PARTY_CATEGORY_SECTION_SOCIAL
    default: THIRD_PARTY_CATEGORY_SECTION_UNSPECIFIED
    title: Category is used to say which exec report section the grade belongs to
  v1ThirdPartyGrade:
    type: object
    properties:
      gradeSection:
        $ref: '#/definitions/v1ThirdPartyCategory'
        title: what section does the grade belong to
      grade:
        type: string
        title: grade for the section
    title: Grade is the section and grade
