swagger: "2.0"
info:
  title: accounts/v2/api.proto
  version: version not set
tags:
  - name: AccountsService
consumes:
  - application/json
produces:
  - application/json
paths:
  /accounts.v2.AccountsService/ActivateProduct:
    post:
      summary: |-
        ActivateProduct is used to activate a marketplace app or addon on a business, without billing for it.
        This is meant only for use by other internal services, basically only order-fulfillment
        Integrations that want to activate products should go through order-fulfillment or sales-orders
      operationId: AccountsService_ActivateProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2ActivateProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ActivateProductRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/ActivateProductWithActivationID:
    post:
      summary: ActivateProductWithActivationID activates a product with the given activation ID
      operationId: AccountsService_ActivateProductWithActivationID
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ActivateProductWithActivationIDRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/ChangeEdition:
    post:
      summary: |-
        ChangeEdition changes the currently activated app edition to a new one, without billing for it
        This is meant only for use by other service
      operationId: AccountsService_ChangeEdition
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2ChangeEditionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ChangeEditionRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/GetMultiActivationStatuses:
    post:
      summary: GetMultiActivationStatuses is used to obtain status and trial information for multiple product/business id pairs
      operationId: AccountsService_GetMultiActivationStatuses
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetMultiActivationStatusesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetMultiActivationStatusesRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/GetMultiProductActivationsForBusiness:
    post:
      summary: GetMultiProductActivations gets multiple activations for apps or addons within the scope of a business
      operationId: AccountsService_GetMultiProductActivationsForBusiness
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetMultiProductActivationsForBusinessResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetMultiProductActivationsForBusinessRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/GetTotalActivationsForProductsAndPartner:
    post:
      summary: GetTotalActivationsForProductsAndPartner returns the total activations for the given products and partner.
      operationId: AccountsService_GetTotalActivationsForProductsAndPartner
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetTotalActivationsForProductsAndPartnerResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetTotalActivationsForProductsAndPartnerRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/ListActiveAccountsForProduct:
    post:
      summary: ListActiveAccounts returns a list of active accounts for a specified Product
      operationId: AccountsService_ListActiveAccountsForProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2ListActiveAccountsForProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ListActiveAccountsForProductRequest'
      tags:
        - AccountsService
  /accounts.v2.AccountsService/ListActiveActivationsForProductAndBusiness:
    post:
      summary: ListActiveActivationsForProductAndBusiness gets all active activations for the given product and business
      operationId: AccountsService_ListActiveActivationsForProductAndBusiness
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2ListActiveActivationsForProductAndBusinessResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ListActiveActivationsForProductAndBusinessRequest'
      tags:
        - AccountsService
definitions:
  BlameDeactivationReasons:
    type: object
    properties:
      choices:
        type: array
        items:
          type: string
        title: A list of provided reasons the user chose for deactivating
      comments:
        type: string
        title: Additional comments provided with regards to why a product was deactivated
  BlameSource:
    type: string
    enum:
      - BLAME_SOURCE_SYSTEM
      - BLAME_SOURCE_USER
    default: BLAME_SOURCE_SYSTEM
  GetMultiActivationStatusesResponseAppsAndAddonsActivationStatuses:
    type: object
    properties:
      businessId:
        type: string
        title: The business ID
      productId:
        type: string
        title: The id of the marketplace app/addon
      status:
        $ref: '#/definitions/v2ActivationStatus'
        title: The status of the activation
      count:
        type: string
        format: int64
        title: The number of times this ActivationStatus has occured for the app
      isTrial:
        type: boolean
        title: Whether or not the activation is a trial
      editionId:
        type: string
        title: The edition ID of the app/addon
  ListActiveAccountsForProductResponseActiveProducts:
    type: object
    properties:
      businessId:
        type: string
      activationId:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v2ActivateProductRequest:
    type: object
    properties:
      businessId:
        type: string
        description: The business ID.
      productId:
        type: string
        description: The marketplace application/addon ID.
      editionId:
        type: string
        title: The edition id of the edition to be activated
      orderFormSubmissionId:
        type: string
        description: The order form submission id, unique per activation.
      activationInfo:
        $ref: '#/definitions/v2Blame'
        title: The blame information for this action
      billingOrderId:
        type: string
        title: The billing order id for the billable item associated with the activation
      backdateToParentActivation:
        type: boolean
        title: Whether the activation date should be aligned with the parent activation, if it exists
      isTrial:
        type: boolean
        title: Whether a trial of the product is being activated or not
      trialDuration:
        type: integer
        format: int32
        title: Duration of the trial in days. Required if is_trial is true, ignored otherwise
      vendorOrderId:
        type: string
        title: The id of the order from the vendor to group products purchased together
  v2ActivateProductResponse:
    type: object
    properties:
      activationId:
        type: string
        description: A unique ID assigned for this specific product activation.
  v2ActivateProductWithActivationIDRequest:
    type: object
    properties:
      businessId:
        type: string
        description: The business ID.
      productId:
        type: string
        description: The marketplace application/addon ID.
      activationId:
        type: string
        description: A unique ID assigned for this specific product activation.
      editionId:
        type: string
        title: The edition id of the edition to be activated
      orderFormSubmissionId:
        type: string
        description: The order form submission id, unique per activation.
      activationInfo:
        $ref: '#/definitions/v2Blame'
        title: The blame information for this action
      billingOrderId:
        type: string
        title: The billing order id for the billable item associated with the activation
      backdateToParentActivation:
        type: boolean
        title: |-
          Whether the activation date should be aligned with the parent activation, if it exists
          Depreacated: use `activated_on` instead
      isTrial:
        type: boolean
        title: Whether a trial of the product is being activated or not
      trialDuration:
        type: integer
        format: int32
        title: Duration of the trial in days. Required if is_trial is true, ignored otherwise
      vendorOrderId:
        type: string
        title: The id of the order from the vendor to group products purchased together
      activatedOn:
        type: string
        format: date-time
        title: The date on which the product was activated; must be in the past; if not provided, the current time will be used
  v2ActivationStatus:
    type: string
    enum:
      - ACTIVATION_STATUS_NOT_SPECIFIED
      - ACTIVATION_STATUS_ACTIVATED
      - ACTIVATION_STATUS_PENDING
      - ACTIVATION_STATUS_CANCELED
      - ACTIVATION_STATUS_DEACTIVATED
    default: ACTIVATION_STATUS_NOT_SPECIFIED
  v2ActiveActivation:
    type: object
    properties:
      businessId:
        type: string
        title: The business the activation is for
      appId:
        type: string
        title: Identifier for the app that the activation is for
      addonId:
        type: string
        title: Identifier for the addon that the activation is for
      activationId:
        type: string
        title: The unique identifier for an activation
      billingOrderId:
        type: string
        title: The billing order id for the billable item associated with the activation
    title: An active app or add-on activation
  v2Blame:
    type: object
    properties:
      source:
        $ref: '#/definitions/BlameSource'
        title: The source of action
      sourceIdentifier:
        type: string
        title: |-
          Optionally used to provide additional information on source
          ie: If source is USER, identifier could be an e-mail
      orderId:
        type: string
        title: ID of the corresponding order in the fulfilment service
      reasons:
        $ref: '#/definitions/BlameDeactivationReasons'
        title: Reasons for a deactivation
  v2ChangeEditionRequest:
    type: object
    properties:
      businessId:
        type: string
        description: The business ID.
      productId:
        type: string
        description: The marketplace application ID.
      activationId:
        type: string
        title: The activation ID of the activation to change editions for
      editionId:
        type: string
        title: The ID of the edition to change to
      billingOrderId:
        type: string
        title: The billing order ID
      changeDate:
        type: string
        format: date-time
        description: When to change to the new edition. If empty, the change will take effect at time of processing.
      changeEditionInfo:
        $ref: '#/definitions/v2Blame'
        title: The blame information for this action
      vendorOrderId:
        type: string
        title: The id of the order from the vendor to group products purchased together
  v2ChangeEditionResponse:
    type: object
    properties:
      activationId:
        type: string
        description: A unique ID assigned for this specific edition change.
  v2GetMultiActivationStatusesRequest:
    type: object
    properties:
      businessIds:
        type: array
        items:
          type: string
        title: The list of business ids to get activation statuses for
  v2GetMultiActivationStatusesResponse:
    type: object
    properties:
      activationStatuses:
        type: array
        items:
          type: object
          $ref: '#/definitions/GetMultiActivationStatusesResponseAppsAndAddonsActivationStatuses'
        title: A list of activation status of a app/addon
  v2GetMultiProductActivationsForBusinessRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business the activation is for
      productActivationIdentifiers:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2ProductActivationForBusinessIdentifiers'
        title: The list of identifiers to get activations for
  v2GetMultiProductActivationsForBusinessResponse:
    type: object
    properties:
      productActivations:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2ProductActivation'
        title: A list of active activations
  v2GetTotalActivationsForProductsAndPartnerRequest:
    type: object
    properties:
      productIds:
        type: array
        items:
          type: string
        description: The product IDs for which to get the total activations.
      partnerId:
        type: string
        description: The partner ID for which to get the total activations.
  v2GetTotalActivationsForProductsAndPartnerResponse:
    type: object
    properties:
      totalActivations:
        type: string
        format: int64
        description: The count of total activations for the given products and partner.
  v2ListActiveAccountsForProductRequest:
    type: object
    properties:
      productId:
        type: string
        title: The app to find active accounts for
      cursor:
        type: string
        title: A cursor to be provided when fetching additional pages of results beyond the first
      pageSize:
        type: string
        format: int64
        title: Size of the page to return
  v2ListActiveAccountsForProductResponse:
    type: object
    properties:
      activeProducts:
        type: array
        items:
          type: object
          $ref: '#/definitions/ListActiveAccountsForProductResponseActiveProducts'
        title: A list of the active accounts' business IDs
      nextCursor:
        type: string
        title: A cursor for the next page of results
      hasMore:
        type: boolean
        title: A flag to indicate there are more pages
  v2ListActiveActivationsForProductAndBusinessRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business you want a list of all activations for
      productId:
        type: string
        title: The app or add-on ID
  v2ListActiveActivationsForProductAndBusinessResponse:
    type: object
    properties:
      activations:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2ActiveActivation'
        title: A list of active activations
  v2ProductActivation:
    type: object
    properties:
      businessId:
        type: string
        title: The business the activation is for
      productId:
        type: string
        title: Identifier for the app or addon that the activation is for
      activationId:
        type: string
        title: The unique identifier for an activation
      editionId:
        type: string
        title: The edition id of the edition on the activation
      isTrial:
        type: boolean
        title: Whether the activation is a trial
      activation:
        type: string
        format: date-time
        title: The UTC time the activation began
      deactivation:
        type: string
        format: date-time
        title: The UTC time the activation ended
    title: An app or add-on activation
  v2ProductActivationForBusinessIdentifiers:
    type: object
    properties:
      productId:
        type: string
        title: Identifier for the app or addon that the activation is for
      activationId:
        type: string
        title: The unique identifier for an activation
