swagger: "2.0"
info:
  title: constant-contact/v1/api.proto
  version: version not set
tags:
  - name: AccountService
  - name: CampaignService
consumes:
  - application/json
produces:
  - application/json
paths:
  /constantcontact.v1.AccountService/GetAccount:
    post:
      operationId: AccountService_GetAccount
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAccountResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAccountRequest'
      tags:
        - AccountService
  /constantcontact.v1.AccountService/ListAccounts:
    post:
      operationId: AccountService_ListAccounts
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListAccountsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListAccountsRequest'
      tags:
        - AccountService
  /constantcontact.v1.AccountService/ListPricingTiers:
    post:
      operationId: AccountService_ListPricingTiers
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListPricingTiersResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListPricingTiersRequest'
      tags:
        - AccountService
  /constantcontact.v1.AccountService/UpdateAccountPlan:
    post:
      operationId: AccountService_UpdateAccountPlan
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1UpdateAccountPlanRequest'
      tags:
        - AccountService
  /constantcontact.v1.CampaignService/GetMulti:
    post:
      operationId: CampaignService_GetMulti
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMultiCampaignsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMultiCampaignsRequest'
      tags:
        - CampaignService
definitions:
  GetMultiCampaignsResponseCampaign:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID
      businessId:
        type: string
        title: Business ID
      campaignId:
        type: string
        title: Campaign ID
      campaignName:
        type: string
        title: Campaign Name
  ListPricingTiersResponsePricingTier:
    type: object
    properties:
      id:
        type: string
        format: int64
        title: ID of a pricing tier
      minContact:
        type: string
        format: int64
        title: The minimum contact list size of a tier (inclusive)
      maxContact:
        type: string
        format: int64
        title: The maximum contact list size of a tier (inclusive)
      contactRangeDisplayString:
        type: string
        title: The string for displaying the contact range
      wholesalePriceInCents:
        type: string
        format: int64
        title: The wholesale price in USD
      retailPriceInCents:
        type: string
        format: int64
        title: The retail price in USD
      plan:
        $ref: '#/definitions/v1AccountPlan'
        title: The corresponding plan (Email/Email Plus) of the pricing tier
    title: PricingTier stands for a single tier
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Account:
    type: object
    properties:
      businessId:
        type: string
        title: Business ID
      pricingTierId:
        type: string
        format: int64
        title: The pricing tier that the business is currently in
      status:
        $ref: '#/definitions/v1AccountStatus'
        title: The current billing status of the account
      plan:
        $ref: '#/definitions/v1AccountPlan'
        title: The current plan of the account
      partnerId:
        type: string
        title: Partner ID of the account
  v1AccountPlan:
    type: string
    enum:
      - ACCOUNT_PLAN_INVALID
      - ACCOUNT_PLAN_EMAIL
      - ACCOUNT_PLAN_EMAIL_PLUS
      - ACCOUNT_PLAN_LITE
      - ACCOUNT_PLAN_STANDARD
      - ACCOUNT_PLAN_PREMIUM
    default: ACCOUNT_PLAN_INVALID
    title: The plan of a constant contact account
  v1AccountStatus:
    type: string
    enum:
      - ACCOUNT_STATUS_INVALID
      - ACCOUNT_STATUS_TRIAL
      - ACCOUNT_STATUS_OPEN
      - ACCOUNT_STATUS_CANCELLED
      - ACCOUNT_STATUS_PENDING_CANCELLATION
      - ACCOUNT_STATUS_TRIAL_END
    default: ACCOUNT_STATUS_INVALID
    title: Possible statuses of a constant contact account
  v1GetAccountRequest:
    type: object
    properties:
      businessId:
        type: string
        title: Business ID
    title: A request to get a constant contact account's status
  v1GetAccountResponse:
    type: object
    properties:
      account:
        $ref: '#/definitions/v1Account'
        title: Description of the account
    title: A response containing information about a constant contact account
  v1GetMultiCampaignsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID
      businessId:
        type: string
        title: Business ID
      campaignIds:
        type: array
        items:
          type: string
        title: One or more campaign ID(s)
    title: The request to get the information of multiple campaigns
  v1GetMultiCampaignsResponse:
    type: object
    properties:
      campaigns:
        type: array
        items:
          type: object
          $ref: '#/definitions/GetMultiCampaignsResponseCampaign'
    title: The response containing the information of multiple campaigns
  v1ListAccountsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID
      pagingOptions:
        $ref: '#/definitions/v1PagedRequestOptions'
        title: Options for how to page the response for this request
    title: A request to list constant contact accounts of a partner
  v1ListAccountsResponse:
    type: object
    properties:
      accounts:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Account'
        title: |-
          Account represents the constant-contact accounts of a business
          List of accounts
      pagingMetadata:
        $ref: '#/definitions/v1PagedResponseMetadata'
        title: Metadata about the paging
  v1ListPricingTiersRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID
    title: List the pricing tiers of a given partner
  v1ListPricingTiersResponse:
    type: object
    properties:
      pricingTiers:
        type: array
        items:
          type: object
          $ref: '#/definitions/ListPricingTiersResponsePricingTier'
        title: List of pricing tiers
    title: ListPricingTiersResponse returns the pricing tiers of a partner
  v1PagedRequestOptions:
    type: object
    properties:
      cursor:
        type: string
        title: cursor can be passed to retrieve the next page of results keyed by the cursor
      pageSize:
        type: string
        format: int64
        title: page_size specifies the number of items to return in the next page
  v1PagedResponseMetadata:
    type: object
    properties:
      nextCursor:
        type: string
        title: A cursor that can be provided to retrieve the next page of results
      hasMore:
        type: boolean
        title: Whether or not more results exist
  v1UpdateAccountPlanRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID
      businessId:
        type: string
        title: Business ID
      plan:
        $ref: '#/definitions/v1AccountPlan'
        title: The current plan of the account
    title: The request to update plan for the account of the given business ID
