swagger: "2.0"
info:
  title: media/v1/api.proto
  version: version not set
tags:
  - name: ImageService
consumes:
  - application/json
produces:
  - application/json
paths:
  /media.v1.ImageService/Create:
    post:
      operationId: ImageService_Create
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateImageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateImageRequest'
      tags:
        - ImageService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CreateImageRequest:
    type: object
    properties:
      servingUrl:
        type: string
        title: The serving_url that is generated after an image is uploaded to google cloud storage
      tags:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Tag'
        title: Tag identifiers for statistics
    title: The CreateImageRequest message comes from a client to create an image, after it has been uploaded
  v1CreateImageResponse:
    type: object
    properties:
      imageId:
        type: string
        title: The image_id for the image indexed in vStore
    title: The CreateImageResponse returns the image_id of the image that is indexed in vStore
  v1Tag:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
    title: Key value pair
