swagger: "2.0"
info:
  title: notifications/v1/provider.proto
  version: version not set
tags:
  - name: NotificationsProvider
consumes:
  - application/json
produces:
  - application/json
paths:
  /notifications.v1.NotificationsProvider/SaveNotification:
    post:
      summary: |-
        SaveNotification from the provider
        NOTE: You DO NOT USE this if you are publishing events to event-broker that deliver notifications, if you ARE using this then you don't need to publish events
      operationId: NotificationsProvider_SaveNotification
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SaveNotificationRequest'
      tags:
        - NotificationsProvider
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  protobufNullValue:
    type: string
    enum:
      - NULL_VALUE
    default: NULL_VALUE
    description: |-
      `NullValue` is a singleton enumeration to represent the null value for the
      `Value` type union.

      The JSON representation for `NullValue` is JSON `null`.

       - NULL_VALUE: Null value.
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1NotificationMedium:
    type: string
    enum:
      - NOTIFICATION_MEDIUM_WEB
      - NOTIFICATION_MEDIUM_EMAIL
    default: NOTIFICATION_MEDIUM_WEB
    title: The Medium that the notification will be sent to
  v1SaveNotificationRequest:
    type: object
    properties:
      notificationTypeId:
        type: string
        description: The ID of the notification type being provided.
      notificationId:
        type: string
        title: The ID of the notification, notifications which already exist will not be updated
      userId:
        type: string
        title: The user the notification is for -- this is a unified user id
      medium:
        $ref: '#/definitions/v1NotificationMedium'
        title: The medium to send the notification for
      notificationTime:
        type: string
        format: date-time
        title: This is the time that the notification will appear as in the stream
      data:
        type: object
        title: |-
          The data for the notification, contains contextual identifiers like account group id,
          and other data useable by the notification template
