swagger: "2.0"
info:
  title: marketplace_packages/v1/buy_it_now_api.proto
  version: version not set
tags:
  - name: BuyItNow
consumes:
  - application/json
produces:
  - application/json
paths:
  /marketplace_packages.v1.BuyItNow/GenerateBuyItNowLink:
    post:
      summary: GenerateBuyItNowLink generates a "Buy It Now" link for a user and package.
      operationId: BuyItNow_GenerateBuyItNowLink
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GenerateBuyItNowLinkResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GenerateBuyItNowLinkRequest'
      tags:
        - BuyItNow
  /marketplace_packages.v1.BuyItNow/GetBuyItNowLinkByLinkID:
    post:
      summary: GetBuyItNowLink gets a "Buy It Now" link for a user and package.
      operationId: BuyItNow_GetBuyItNowLinkByLinkID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetBuyItNowLinkByLinkIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetBuyItNowLinkByLinkIDRequest'
      tags:
        - BuyItNow
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v1BuyItNowLink:
    type: object
    properties:
      accountGroupId:
        type: string
        description: The ID of the account group for which the link was generated.
      userId:
        type: string
        description: The ID of the user for which the link was generated.
      packageId:
        type: string
        description: The ID of the package for which the link was generated.
      linkId:
        type: string
        description: The ID of the "Buy It Now" link.
      created:
        type: string
        format: date-time
        description: The created time of the link.
      link:
        type: string
        description: The constructed link to the store package (e.g. https://vendasta-training.smblogin.com/buy-it-now/<link_id>).
  v1GenerateBuyItNowLinkRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        description: / The ID of the account group for which the link was generated.
      userId:
        type: string
        description: The ID of the user for which the link was generated.
      packageId:
        type: string
        description: The ID of the package for which the link was generated.
  v1GenerateBuyItNowLinkResponse:
    type: object
    properties:
      link:
        $ref: '#/definitions/v1BuyItNowLink'
        description: The generated link for the user and package.
      shortenedUrl:
        type: string
        title: The shortened version of the buy-it-now link URL (e.g. https://1l.ink/abc123)
  v1GetBuyItNowLinkByLinkIDRequest:
    type: object
    properties:
      linkId:
        type: string
        description: The ID of the generated "Buy It Now" link.
  v1GetBuyItNowLinkByLinkIDResponse:
    type: object
    properties:
      link:
        $ref: '#/definitions/v1BuyItNowLink'
        description: The generated link for the user and package.
