swagger: "2.0"
info:
  title: social_posts/v2/blog_connection.proto
  version: version not set
tags:
  - name: BlogConnectionService
consumes:
  - application/json
produces:
  - application/json
paths:
  /socialposts.v2.BlogConnectionService/Create:
    post:
      operationId: BlogConnectionService_Create
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2CreateBlogConnectionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2CreateBlogConnectionRequest'
      tags:
        - BlogConnectionService
  /socialposts.v2.BlogConnectionService/Delete:
    post:
      operationId: BlogConnectionService_Delete
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2DeleteBlogConnectionRequest'
      tags:
        - BlogConnectionService
  /socialposts.v2.BlogConnectionService/Get:
    post:
      operationId: BlogConnectionService_Get
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetBlogConnectionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetBlogConnectionRequest'
      tags:
        - BlogConnectionService
  /socialposts.v2.BlogConnectionService/List:
    post:
      operationId: BlogConnectionService_List
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2ListBlogConnectionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2ListBlogConnectionRequest'
      tags:
        - BlogConnectionService
  /socialposts.v2.BlogConnectionService/Update:
    post:
      operationId: BlogConnectionService_Update
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2UpdateBlogConnectionRequest'
      tags:
        - BlogConnectionService
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v2BlogConnection:
    type: object
    properties:
      socialServiceId:
        type: string
        title: The unique identifier of the blog post connection
      name:
        type: string
        title: The name of the blog post connection
      businessId:
        type: string
        title: The business id of the blog post connection
      partnerId:
        type: string
        title: The partner id of the blog post connection
      apiKey:
        type: string
        title: The api key of the blog post connection
      logo:
        type: string
        title: The logo of the blog post connection
      pluginStatus:
        type: boolean
        title: The plugin status of the blog post connection
      version:
        type: string
        title: The version of the wordpress plugin
      created:
        type: string
        format: date-time
        title: Connection created date time
      updated:
        type: string
        format: date-time
        title: Connection updated date time
      siteUrl:
        type: string
        title: The root url of the website
  v2CreateBlogConnectionRequest:
    type: object
    properties:
      name:
        type: string
        title: The name of the blog post connection
      businessId:
        type: string
        title: The business id of the blog post connection
      partnerId:
        type: string
        title: The partner id of the blog post connection
      apiKey:
        type: string
        title: The api key of the blog post connection
      logo:
        type: string
        title: The logo of the blog post connection
      pluginStatus:
        type: boolean
        title: The plugin status of the blog post connection
      version:
        type: string
        title: The version of the wordpress plugin
      siteUrl:
        type: string
        title: The root url of the website
  v2CreateBlogConnectionResponse:
    type: object
    properties:
      socialServiceId:
        type: string
        title: Unique identifier of the connection
  v2DeleteBlogConnectionRequest:
    type: object
    properties:
      socialServiceId:
        type: string
        title: The unique identifier of the blog post connection to delete connection
      businessId:
        type: string
        title: The business id of the blog post connection
  v2GetBlogConnectionRequest:
    type: object
    properties:
      socialServiceId:
        type: string
        title: The unique identifier of the blog post connection
  v2GetBlogConnectionResponse:
    type: object
    properties:
      blogConnection:
        $ref: '#/definitions/v2BlogConnection'
        title: The blog post connection
  v2ListBlogConnectionRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business id of the blog post connection
      pageSize:
        type: string
        format: int64
        title: Page size of the connection
      cursor:
        type: string
        title: Cursor
  v2ListBlogConnectionResponse:
    type: object
    properties:
      blogConnections:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2BlogConnection'
        title: List of connections under a business id
      cursor:
        type: string
      hasMore:
        type: boolean
  v2UpdateBlogConnectionRequest:
    type: object
    properties:
      socialServiceId:
        type: string
        title: The unique identifier of the blog post connection
      name:
        type: string
        title: The name of the blog post connection
      businessId:
        type: string
        title: The business id of the blog post connection
      partnerId:
        type: string
        title: The partner id of the blog post connection
      apiKey:
        type: string
        title: The api key of the blog post connection
      logo:
        type: string
        title: The logo of the blog post connection
      pluginStatus:
        type: boolean
        title: The plugin status of the blog post connection
      version:
        type: string
        title: The version of the wordpress plugin
      siteUrl:
        type: string
        title: The root url of the website
