swagger: "2.0"
info:
  title: social_posts/v2/campaign.proto
  version: version not set
tags:
  - name: CampaignService
consumes:
  - application/json
produces:
  - application/json
paths:
  /socialposts.v2.CampaignService/Create:
    post:
      operationId: CampaignService_Create
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2CreateCampaignResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2CreateCampaignRequest'
      tags:
        - CampaignService
  /socialposts.v2.CampaignService/Delete:
    post:
      operationId: CampaignService_Delete
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2DeleteCampaignRequest'
      tags:
        - CampaignService
  /socialposts.v2.CampaignService/Get:
    post:
      operationId: CampaignService_Get
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetCampaignResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetCampaignRequest'
      tags:
        - CampaignService
  /socialposts.v2.CampaignService/GetMulti:
    post:
      operationId: CampaignService_GetMulti
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetMultiCampaignsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetMultiCampaignsRequest'
      tags:
        - CampaignService
  /socialposts.v2.CampaignService/Update:
    post:
      operationId: CampaignService_Update
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2UpdateCampaignRequest'
      tags:
        - CampaignService
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v2Campaign:
    type: object
    properties:
      campaignName:
        type: string
        title: Name of the campaign
      businessId:
        type: string
        title: The business id of the campaign post
      partnerId:
        type: string
        title: The partner id of the campaign post
      id:
        type: string
        title: The unique id of the campaign
  v2CreateCampaignRequest:
    type: object
    properties:
      name:
        type: string
        title: The name of the campaign
      businessId:
        type: string
        title: The business id of the blog post connection
      partnerId:
        type: string
        title: The partner id of the campaign post
  v2CreateCampaignResponse:
    type: object
    properties:
      campaignId:
        type: string
        title: This is identifier for the campaign
  v2DeleteCampaignRequest:
    type: object
    properties:
      campaignId:
        type: string
        title: The unique id of the campaign
      businessId:
        type: string
        title: The business id of the campaign post
  v2GetCampaignRequest:
    type: object
    properties:
      campaignId:
        type: string
        title: The unique id of the campaign
      businessId:
        type: string
        title: The business id of the campaign post
  v2GetCampaignResponse:
    type: object
    properties:
      campaign:
        $ref: '#/definitions/v2Campaign'
  v2GetMultiCampaignsRequest:
    type: object
    properties:
      businessId:
        type: string
        description: The unique identifier of the business (Used for access check).
      campaignId:
        type: array
        items:
          type: string
        title: A list of internal identifier of campaigns
  v2GetMultiCampaignsResponse:
    type: object
    properties:
      campaigns:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2Campaign'
        title: A array of campaigns
  v2UpdateCampaignRequest:
    type: object
    properties:
      campaignId:
        type: string
        title: This is identifier for the campaign
      name:
        type: string
        title: The name of the campaign
      businessId:
        type: string
        title: The business id of the campaign post
      partnerId:
        type: string
        title: The partner id of the campaign post
