swagger: "2.0"
info:
  title: social_posts/v2/chat_bot_v2.proto
  version: version not set
tags:
  - name: ChatBotV2
consumes:
  - application/json
produces:
  - application/json
paths:
  /socialposts.v2.ChatBotV2/SendMessageV2:
    post:
      operationId: ChatBotV2_SendMessageV2
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2SendMessageV2Response'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2SendMessageV2Request'
      tags:
        - ChatBotV2
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v2ChatMessage:
    type: object
    properties:
      role:
        $ref: '#/definitions/v2Role'
      content:
        type: string
  v2Role:
    type: string
    enum:
      - INVALID
      - USER
      - AI_BOT
    default: INVALID
  v2SendMessageV2Request:
    type: object
    properties:
      businessId:
        type: string
      partnerId:
        type: string
      marketId:
        type: string
      customInstructions:
        type: string
      messages:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2ChatMessage'
      brandId:
        type: string
        title: Included brand id to check the multilocation contexts
  v2SendMessageV2Response:
    type: object
    properties:
      messageResponse:
        type: string
