swagger: "2.0"
info:
  title: social_posts/v2/chat_bot.proto
  version: version not set
tags:
  - name: ChatBot
consumes:
  - application/json
produces:
  - application/json
paths:
  /socialposts.v2.ChatBot/EndChat:
    post:
      operationId: ChatBot_EndChat
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2EndChatRequest'
      tags:
        - ChatBot
  /socialposts.v2.ChatBot/SendMessage:
    post:
      operationId: ChatBot_SendMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2SendMessageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2SendMessageRequest'
      tags:
        - ChatBot
  /socialposts.v2.ChatBot/StartChat:
    post:
      operationId: ChatBot_StartChat
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2StartChatResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2StartChatRequest'
      tags:
        - ChatBot
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v2Action:
    type: object
    properties:
      actionType:
        $ref: '#/definitions/v2ActionType'
        description: Action type represent what type content needed from AI.
      actionPayload:
        type: string
        title: action payload is the param which hold the text to be modified
  v2ActionType:
    type: string
    enum:
      - RESPOND
      - CHANGE_TONE
    default: RESPOND
  v2EndChatRequest:
    type: object
    properties:
      threadId:
        type: string
        title: This threadID is required to delete the thread from the Assistant (or else a thread may lasts upto 60 days)
  v2MetadataV2:
    type: object
    properties:
      name:
        type: string
        title: The property name or key
      value:
        type: string
        title: The property value associated with the name/key
    title: Stored as key/value pairs can contain generic metadata information
  v2SendMessageRequest:
    type: object
    properties:
      messageContent:
        type: string
        title: The text that will be sent to AI to create an AI text model
      threadId:
        type: string
        title: Thread Id used to get the conversation details of Thread
      actions:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2Action'
        title: Action params are used to generate a text based on additional info
  v2SendMessageResponse:
    type: object
    properties:
      messageResponse:
        type: string
        description: Message Response is Text where it holds the actual text model received from AI based on our input.
      threadId:
        type: string
        title: Thread Id used to get the conversation details of Thread
  v2StartChatRequest:
    type: object
    properties:
      metadata:
        type: array
        items:
          type: object
          $ref: '#/definitions/v2MetadataV2'
        title: Meta data to exchange info like AGID/PartnerId as flexible for AI knowledge
  v2StartChatResponse:
    type: object
    properties:
      assistantId:
        type: string
        description: Assistant-ID used for start Thread.
      threadId:
        type: string
        title: Thread ID used for message conversation
