openapi: 3.0.0
info:
  title: Platform REST APIs
  version: Evergreen
servers:
  - url: 'https://prod.apigateway.co/platform'
    description: Production
  - description: Demo
    url: 'https://demo.apigateway.co/platform'
  - description: Local
    url: '{local}/platform'
  - url: 'http://localhost:11001/platform'
    description: Localhost
paths:
  /salesContacts:
    post:
      summary: Create Sales Contact
      operationId: post-salesContacts
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Use this operation to create a new Sales Contact for a business.

        An email and business location must be provided when creating a contact.

        Note: Currently when creating a contact you must specify exactly 1 Business Location id for it to be linked to. We intend to expand this limit.
      security:
        - OAuth2Demo:
            - sales.contact
        - OAuth2Prod:
            - sales.contact
      tags:
        - Sales Contacts
    options:
      operationId: options-salesContacts
      tags:
        - Options
        - Sales Contacts
      summary: List valid HTTP verbs for /salesContacts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/salesContacts/{id}':
    get:
      summary: Get Sales Contact
      tags:
        - Sales Contacts
      operationId: get-salesContacts-id
      security:
        - OAuth2Demo:
            - sales.contact
        - OAuth2Prod:
            - sales.contact
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Fetch the current values for the specified sales contact
    options:
      operationId: options-salesContacts-id
      summary: 'List valid HTTP verbs for /salesContacts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Contacts
  /businessLocations:
    post:
      summary: Create Business Location
      operationId: post-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
      security:
        - OAuth2Demo:
            - business
        - OAuth2Prod:
            - business
      tags:
        - Business Locations
    options:
      operationId: options-businessLocations
      summary: List valid HTTP verbs for /businessLocations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Locations
    get:
      summary: List Business Locations
      operationId: get-businessLocations
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of business locations
      security:
        - OAuth2Demo:
            - business
            - 'business:read'
        - OAuth2Prod:
            - business
            - 'business:read'
      tags:
        - Business Locations
      x-lifecycle:
        status: trustedTester
  '/businessLocations/{id}':
    get:
      summary: Get Business Location
      tags:
        - Business Locations
      operationId: get-businessLocations-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns basic data about the business location.
      security:
        - OAuth2Demo:
            - business
            - 'business:read'
        - OAuth2Prod:
            - business
            - 'business:read'
    options:
      operationId: options-businessLocations-id
      summary: 'List valid HTTP verbs for /businessLocations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Locations
    patch:
      summary: Update Business Location
      operationId: patch-businessLocations-id
      tags:
        - Business Locations
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update the existing business location.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2Demo:
            - business
        - OAuth2Prod:
            - business
  /users:
    post:
      summary: Create User
      operationId: post-users
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.partner.data.id`
        - `attributes.email`
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
    options:
      operationId: options-users
      summary: List valid HTTP verbs for /users
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    get:
      summary: List Users
      operationId: get-users
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of users
      security:
        - OAuth2Demo:
            - user.admin
            - user.list
        - OAuth2Prod:
            - user.admin
            - user.list
      tags:
        - Users
      x-lifecycle:
        status: trustedTester
  '/users/{id}':
    get:
      summary: Get User
      tags:
        - Users
      operationId: get-users-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns information about a single user. The fields you are able to use will be affected by the combination of scopes that you were granted access to.
      security:
        - OAuth2Demo:
            - user.admin
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.permission
            - self.user.admin
            - 'self.user.contact:read'
            - 'user:read'
            - openid
            - profile
            - email
            - phone
            - address
        - OAuth2Prod:
            - user.admin
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.permission
            - self.user.admin
            - 'self.user.contact:read'
            - 'user:read'
            - openid
            - profile
            - email
            - phone
            - address
    options:
      operationId: options-users-id
      summary: 'List valid HTTP verbs for /users/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    patch:
      summary: Update User
      operationId: patch-users-id
      tags:
        - Users
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Update the existing user.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: proposed
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
    delete:
      summary: Delete User
      operationId: delete-users-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Deleting a user will remove personal data from it and prevent the ID from being used again in the future.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
      x-lifecycle:
        status: trustedTester
  /purchases:
    get:
      summary: List Purchases
      tags:
        - Purchases
      operationId: get-purchases
      security:
        - OAuth2Demo:
            - financial
        - OAuth2Prod:
            - financial
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of wholesale purchases made.
    options:
      operationId: options-purchases
      summary: List valid HTTP verbs for /purchases
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Purchases
  /businessCategories:
    get:
      summary: List Business Categories
      operationId: get-businessCategories
      tags:
        - Business Categories
      security:
        - OAuth2Demo:
            - business
        - OAuth2Prod:
            - business
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of business categories
    options:
      operationId: options-businessCategories
      summary: List valid HTTP verbs for /businessCategories
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Categories
  /orders:
    post:
      summary: Create Order
      tags:
        - Orders
      operationId: post-orders
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Use this operation to create a new order for a business.

        By default all orders created by API start out in the `processing` status and do not require approval by either the partner admin or SMB admin. You may create orders with a statusCode of `draft` to simply pre populate the order and then finish processing within the platform. To create an order and send it to admins for approval use the statusCode of `submitted`. 

        <!-- theme: warning -->
        >Note: For newly created Business Locations/Sales Account it does take a few seconds for the newly created account to be replicated to the billing system and for the billing system to setup some additional records for it. It is usually under 5 seconds  but may take a little longer on high traffic days.
        >
        >We recommend checking for the `NotReady` status code in the error response and retrying on that with an exponential backoff.
      security:
        - OAuth2Demo:
            - order
        - OAuth2Prod:
            - order
    options:
      operationId: options-orders
      summary: 'List valid HTTP verbs for /orders/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
    get:
      summary: List Orders
      operationId: get-orders
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of orders.
      security:
        - OAuth2Demo:
            - order
            - 'order:read'
        - OAuth2Prod:
            - order
            - 'order:read'
      tags:
        - Orders
      x-lifecycle:
        status: trustedTester
  '/orders/{id}':
    get:
      summary: Get Order
      tags:
        - Orders
      operationId: get-orders-id
      security:
        - OAuth2Demo:
            - order
            - 'order:read'
        - OAuth2Prod:
            - order
            - 'order:read'
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Fetch the current values for the specified order.
    options:
      operationId: options-order-id
      summary: 'List valid HTTP verbs for /orders/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
  '/orders/{id}/relationships/customFields':
    get:
      summary: Get Custom Fields ID
      operationId: get-orderCustomFieldsID-by-order
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a reference to the custom metadata for this sales order. Use the path without `/relationships/` in it to get the actual data.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - order
        - OAuth2Prod:
            - order
      x-lifecycle:
        status: trustedTester
      tags:
        - Orders
    options:
      summary: 'List valid HTTP verbs for /orders/{id}/relationships/customFields'
      operationId: options-orderCustomFieldsID-by-order
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
  '/orders/{id}/customFields':
    get:
      summary: Get Custom Fields
      operationId: get-orderCustomFields-by-order
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        This endpoint acts like a alias to [Get Order Custom Fields by ID endpoint](b3A6MzYxMTM5MTY-get-order-custom-data-by-id). It returns custom fields about a sales order.
      security:
        - OAuth2Demo:
            - order
        - OAuth2Prod:
            - order
      x-lifecycle:
        status: trustedTester
      tags:
        - Orders
    options:
      summary: 'List valid HTTP verbs for /orders/{id}/customFields'
      operationId: options-orderCustomFields-by-order
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
  '/orderCustomFields/{id}':
    patch:
      summary: Update Custom Fields
      operationId: patch-orderCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to an Order
      security:
        - OAuth2Demo:
            - order
        - OAuth2Prod:
            - order
      tags:
        - Order Custom Fields
    get:
      summary: Get Custom Fields by ID
      operationId: get-orderCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields about a sales order.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - order
        - OAuth2Prod:
            - order
      x-lifecycle:
        status: trustedTester
      tags:
        - Order Custom Fields
    options:
      summary: 'List valid HTTP verbs for /orderCustomFields/{id}'
      operationId: options-orderCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Order Custom Fields
  '/users/{id}/relationships/businessLocations':
    options:
      operationId: options-users-id-relationships-businessLocations
      summary: 'List valid HTTP verbs for /users/{id}/relationships/businessLocations'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    post:
      summary: Associate user with location
      operationId: post-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Users can be granted access to business location(s) using the POST operation. After the operation completes, the user will have access to all their previous business locations plus any new locations in the POST request. If the user already has access to one or more of the specified locations they will be silently ignored.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
    get:
      summary: Get user locations
      operationId: get-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Retrieves the business locations to which the User is associated.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
    patch:
      summary: Replace user location access
      operationId: patch-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Users can be granted access to business location(s) or removed from access to business location(s) using the PATCH operation. After the operation completes, the user will have access only to those business locations specified in the request body (if any).
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
    delete:
      summary: Dissociate user from location
      operationId: delete-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Access to business locations can be removed from a user with the DELETE operation. If the user does not already have access to one or more of the specified locations, they will be silently ignored.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - Users
  /automationRuns:
    post:
      summary: Create automation run
      tags:
        - Automation Runs
      operationId: post-autoamtionruns
      security:
        - OAuth2Demo:
            - business
        - OAuth2Prod:
            - business
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Create an automation run (to trigger a preconfigured automation)
    options:
      operationId: options-automationruns-id
      summary: List valid HTTP verbs for /automationRuns
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Automation Runs
  /automations:
    options:
      operationId: options-automations
      tags:
        - Options
        - Automations
      summary: List valid HTTP verbs for /automations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
    get:
      summary: List Automations
      operationId: list-automations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Returns a list of automations.
      security:
        - OAuth2Demo:
            - 'automation:read'
        - OAuth2Prod:
            - 'automation:read'
      tags:
        - Automations
  '/automations/{id}':
    options:
      operationId: options-automations-id
      tags:
        - Options
        - Automations
      summary: 'List valid HTTP verbs for /automations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
    get:
      summary: Get Automation
      operationId: get-automation-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns basic data about the automation.
      security:
        - OAuth2Demo:
            - 'automation:read'
        - OAuth2Prod:
            - 'automation:read'
      tags:
        - Automations
  /salesAccounts:
    post:
      summary: Create Sales Account
      operationId: post-salesAccounts
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      tags:
        - Sales Accounts
    options:
      operationId: options-salesAccounts
      summary: List valid HTTP verbs for /salesAccounts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
    get:
      summary: List Sales Accounts
      operationId: get-salesAccounts
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of sales accounts
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      tags:
        - Sales Accounts
      x-lifecycle:
        status: trustedTester
  '/salesAccounts/{id}':
    get:
      summary: Get Sales Accounts
      operationId: get-salesAccounts-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns basic data about the sales account.
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      tags:
        - Sales Accounts
    options:
      operationId: options-salesAccounts-by-id
      summary: 'List valid HTTP verbs for /salesAccounts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
    patch:
      summary: Update Sales Account
      operationId: patch-salesAccounts-by-id
      tags:
        - Sales Accounts
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update the existing business location.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
  /subscriptionAssignments:
    get:
      summary: List Subscription Assignments
      operationId: get-subscriptionAssignments
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Subscription Assignments
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a list of subscription assignments based on the provided filters. 

        Currently you must filter the list to a single business location at a time using `filter[businessLocationId]`

        You will receive a different record for each subscription purchased for multi-activatable products.
    options:
      summary: List valid HTTP verbs for /subscriptionAssignments
      operationId: options-subscriptionAssignments
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Subscription Assignments
  /subscriptions:
    get:
      summary: List Subscriptions
      operationId: get-subscriptions
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a list of subscriptions based on the provided filters. 

        Currently you can filter the list baseed on your partnerID using `filter[partner.id]`

        You will receive a different record for each subscription purchased for multi-activatable products.
      tags:
        - Subscriptions
    options:
      summary: List valid HTTP verbs for /subscriptions
      operationId: options-subscriptions
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Subscriptions
  '/subscriptionAssignments/{id}':
    get:
      summary: Get a particular Subscription Assignment
      operationId: get-subscriptionAssignments-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Fetch the details of a specific subscription assignment by id.
      tags:
        - Subscription Assignments
      x-lifecycle:
        status: proposed
    options:
      summary: 'List valid HTTP verbs for /subscriptionAssignments/{id}'
      operationId: options-subscriptionAssignment-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Subscription Assignments
  '/subscriptionAssignments/{id}/actions/requestCancellation':
    post:
      summary: Cancel Subscription Assignment
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used for cancelling subscription assignments.

        By default all cancel request uses DeactivationType as a DeactivationTypeCancel which indicate we should turn the item off at the items anniversary date, or commitment date, whichever is later. So product is still active till the anniversary date.
      tags:
        - Subscription Assignments
      x-lifecycle:
        status: proposed
      operationId: cancel-subscriptionAssignments-by-id
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
    options:
      summary: 'List valid HTTP verbs for /subscriptionAssignments/{id}/actions/requestCancellation'
      operationId: options-subscriptionAssignment-requestCancellationAction
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Subscription Assignments
  '/salesAccounts/{id}/relationships/customFields':
    get:
      summary: Get Custom Fields ID
      operationId: get-salesAccountCustomFieldsID-by-salesAccount
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a reference to the custom metadata for this sales account. Use the path without `/relationships/` in it to get the actual data.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Sales Accounts
    options:
      summary: 'List valid HTTP verbs for /salesAccounts/{id}/relationships/customFields'
      operationId: options-salesAccountCustomFieldsID-by-salesAccount
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
  '/salesAccounts/{id}/customFields':
    get:
      summary: Get Custom Fields
      operationId: get-salesAccountCustomFields-by-salesAccount
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        This endpoint acts like a alias to [Get Sales Account Custom Fields by ID endpoint](b3A6MzYxMTM5MTY-get-sales-account-custom-data-by-id). It returns custom fields about a sales account.
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Sales Accounts
    options:
      summary: 'List valid HTTP verbs for /salesAccounts/{id}/customFields'
      operationId: options-salesAccountCustomFields-by-salesAccount
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
  '/salesAccountCustomFields/{id}':
    patch:
      summary: Update Custom Fields
      operationId: patch-salesAccountCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to a Sales Account
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      tags:
        - Sales Account Custom Fields
    get:
      summary: Get Custom Fields by ID
      operationId: get-salesAccountCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields about a sales account.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - sales.account
        - OAuth2Prod:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Sales Account Custom Fields
    options:
      summary: 'List valid HTTP verbs for /salesAccountCustomFields/{id}'
      operationId: options-salesAccountCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Account Custom Fields
  '/users/{id}/customFields':
    get:
      summary: Get Custom Fields
      operationId: get-userCustomFields-by-userid
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        This endpoint acts like a alias to [Get User Custom Fields by ID endpoint](b3A6MzczMDUyMjU-get-custom-fields-by-id). It returns custom fields for a user.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      x-lifecycle:
        status: trustedTester
      tags:
        - Users
    options:
      summary: 'List valid HTTP verbs for /users/{id}/customFields'
      operationId: options-userCustomFields-by-userid
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - User Custom Fields
  '/users/{id}/actions/sendWelcomeEmail':
    get:
      summary: Send Welcome Email
      operationId: get-sendWelcomeEmail-by-userid
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        An email will be sent to the already created user whose user id is passed in the request.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      x-lifecycle:
        status: trustedTester
      tags:
        - Users
        - Send Welcome Email
    options:
      summary: 'List valid HTTP verbs for/users/{id}/actions/sendWelcomeEmail'
      operationId: options-sendWelcomeEmail-by-userid
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Send Welcome Email
  '/userCustomFields/{id}':
    patch:
      summary: Update Custom Fields
      operationId: patch-userCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to a User
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      tags:
        - User Custom Fields
    get:
      summary: Get Custom Fields by ID
      operationId: get-userCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields about a user.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - user.admin
        - OAuth2Prod:
            - user.admin
      x-lifecycle:
        status: trustedTester
      tags:
        - User Custom Fields
    options:
      summary: 'List valid HTTP verbs for /userCustomFields/{id}'
      operationId: options-userCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - User Custom Fields
  '/productCustomFields/{id}':
    patch:
      summary: Update Custom Fields for a product
      operationId: patch-productCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to a Product
      security:
        - OAuth2Demo:
            - product
        - OAuth2Prod:
            - product
      tags:
        - Product Custom Fields
    get:
      summary: Get Product Custom Fields by ID
      operationId: get-productCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields for a product.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2Demo:
            - product
        - OAuth2Prod:
            - product
      x-lifecycle:
        status: trustedTester
      tags:
        - Product Custom Fields
    options:
      summary: 'List valid HTTP verbs for /productCustomFields/{id}'
      operationId: options-productCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Product Custom Fields
  /countries:
    get:
      summary: List Countries
      operationId: get-countries
      tags:
        - Countries
      security:
        - OAuth2Demo:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
        - OAuth2Prod:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of countries. 

        To see the regions (state/province) within a country use [/platform/countryRegions?filter[countryCode]=yourcode](platform.yaml/paths/~1countryRegions/get)
    options:
      operationId: options-countries
      summary: List valid HTTP verbs for /countries
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Countries
  '/countries/{id}':
    get:
      summary: Get Country
      operationId: get-countries-id
      tags:
        - Countries
      security:
        - OAuth2Demo:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
        - OAuth2Prod:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Get a specific country by id
    options:
      operationId: options-countries-id
      summary: 'List valid HTTP verbs for /countries/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Countries
  /countryRegions:
    get:
      summary: List Country Regions
      operationId: get-country-regions
      tags:
        - Countries
      security:
        - OAuth2Demo:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
        - OAuth2Prod:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of regions within a country. 

        Note: Our list of regions currently updates based on data provided by Google. You will find that countries that do not normally use regions in their addresses do not have any listed here.
    options:
      operationId: options-countryRegions
      summary: List valid HTTP verbs for /countryRegions
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Countries
  '/countryRegions/{id}':
    get:
      summary: Get Country Region
      operationId: get-country-regions-id
      tags:
        - Countries
      security:
        - OAuth2Demo:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
        - OAuth2Prod:
            - sales.contact
            - business
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.admin
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - sales.account
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Get a specific country region's name by id
    options:
      operationId: options-countryRegions-id
      summary: 'List valid HTTP verbs for /countryRegions/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Countries
  /proposals:
    get:
      summary: List Proposals
      operationId: get-proposals
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Testers`

        Produces a list of Proposals, sorted by the most recently updated proposals.

        **Note**: The following attributes attributes are unavailable in this `LIST` request:
        - `lineItems`
        - `content` 
        *Please perform a `GET` request to receive the above attributes for a specific proposal.*
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
      tags:
        - Proposals
      x-lifecycle:
        status: trustedTester
    post:
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Create a document that can be used by Proposal Builder.

        *CreatorOrganization is required*
      summary: Create Proposal
      operationId: post-proposals
      tags:
        - Proposals
    options:
      operationId: options-proposals
      summary: List valid HTTP verbs for /proposals
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Proposals
  '/proposals/{id}':
    get:
      summary: Get Proposal
      tags:
        - Proposals
      operationId: get-proposals-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a proposal.
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
    options:
      operationId: options-proposals-id
      summary: 'List valid HTTP verbs for /proposals/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Proposals
    patch:
      summary: Update Proposal
      operationId: patch-proposals-id
      tags:
        - Proposals
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update an existing Proposal.

        Only the root ID and type fields are required. All other fields are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
  /proposalTemplates:
    get:
      summary: List Proposal Templates
      operationId: get-proposalTemplates
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of proposal templates, sorted by the most recently updated proposal templates.

        **Note**: The following attributes attributes are unavailable in this `LIST` request:
        - `lineItems`
        - `content` 
        *Please perform a `GET` request to receive the above attributes for a specific proposal template.*
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
      tags:
        - Proposals
      x-lifecycle:
        status: trustedTester
    post:
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Create a proposal template that can be used by Proposal Builder.

        *CreatorOrganization is required*
      summary: Create Proposal Template
      operationId: post-proposalTemplates
      tags:
        - Proposals
    options:
      operationId: options-proposalTemplates
      summary: List valid HTTP verbs for /proposalTemplates
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Proposals
  '/proposalTemplates/{id}':
    get:
      summary: Get Proposal Template
      tags:
        - Proposals
      operationId: get-proposalTemplates-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns a proposal template.
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
    options:
      operationId: options-proposalTemplates-id
      summary: 'List valid HTTP verbs for /proposalTemplates/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Proposals
    patch:
      summary: Update Proposal Template
      operationId: patch-proposalTemplates-id
      tags:
        - Proposals
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update the existing proposal template.

        Only the root ID and type fields are required. All other fields are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2Demo:
            - sales.proposals
        - OAuth2Prod:
            - sales.proposals
  '/partnerActivatableProducts/{id}':
    get:
      summary: Get Partner Activatable Product
      operationId: get-partnerActivatableProducts-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns the details of a product listed in a reseller's store for a known id.
      security:
        - OAuth2Demo:
            - product
            - partner
        - OAuth2Prod:
            - product
            - partner
      tags:
        - Partner Activatable Products
      x-lifecycle:
        status: trustedTester
    options:
      summary: List valid HTTP verbs for
      operationId: options-partnerActivatableProducts-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Partner Activatable Products
  /partnerActivatableProducts:
    get:
      summary: List Partner Activatable Products
      operationId: get-partnerActivatableProducts
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Provides a list of products that can be activated by a partner for their customers. 
        You must filter the list to a single partner using the `filter[partner.id]=PID` query param. 
        Sorted by the whiteLabelName field in ascending order.
      security:
        - OAuth2Demo:
            - partner
            - product
        - OAuth2Prod:
            - partner
            - product
      x-lifecycle:
        status: trustedTester
      tags:
        - Partner Activatable Products
    options:
      summary: List valid HTTP verbs for /partnerActivatableProducts
      operationId: options-partnerActivatableProducts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Partner Activatable Products
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2Demo:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            'business:read': Read only access to business details
            business: Read-write access to business details
            partner: Read-write access to details about your partner
            financial: Read-write access to financial details
            order: Read-write access to order details
            'order:read': Read only access to order details
            'user.profile:read': Read access to the profile fields of all categories of users
            'user.contact:read': 'Read access to the contact info (email, phone, address) of all categories of users'
            'user.permission:read': 'Read access to the permission info (accessible locations, features and roles) of all categories of users'
            user.permission: 'Read-write access to the permission info (accessible locations, features and roles) of all categories of users'
            user.admin: Read-write access to manage all users
            'user:read': Read only access to all users
            user.list: '''Allows searching for users based on a set of filters. (ex: email, name, category, organization). Without this scope an exact user id is required.'
            self.user.admin: 'Allows editing the profile, contact info and profile image for the current user.'
            'self.user.contact:read': 'Read access to the contact info (email, phone, address) of the current user.'
            openid: Allows getting the user id of the current user
            profile: 'Readonly access to the user profile, including name, locale, and language preferences.'
            email: Allows readonly access to the email of the current user.
            phone: Allows readonly access to the phone numbers of the current user.
            address: Allows readonly access to the address of the current user.
            sales.account: Allows read-write access to account records
            sales.proposals: Allows read-write access to proposals
            product: Read access to the product details
            'automation:read': Read only access to automations
    OAuth2Prod:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-prod.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-prod.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            'business:read': Read only access to business details
            business: Read-write access to business details
            partner: Read-write access to details about your partner
            financial: Read-write access to financial details
            'order:read': Read only access to order details
            order: Read-write access to order details
            'user.profile:read': Read access to the profile fields of all categories of users
            'user.contact:read': 'Read access to the contact info (email, phone, address) of all categories of users'
            'user.permission:read': 'Read access to the permission info (accessible locations, features and roles) of all categories of users'
            user.permission: 'Read-write access to the permission info (accessible locations, features and roles) of all categories of users'
            user.admin: Read-write access to manage all users
            'user:read': Read only access to all users
            user.list: '''Allows searching for users based on a set of filters. (ex: email, name, category, organization). Without this scope an exact user id is required.'
            self.user.admin: 'Allows editing the profile, contact info and profile image for the current user.'
            'self.user.contact:read': 'Read access to the contact info (email, phone, address) of the current user.'
            openid: Allows getting the user id of the current user
            profile: 'Readonly access to the user profile, including name, locale, and language preferences.'
            email: Allows readonly access to the email of the current user.
            phone: Allows readonly access to the phone numbers of the current user.
            address: Allows readonly access to the address of the current user.
            sales.account: Allows read-write access to account records
            sales.proposals: Allows read-write access to proposals
            product: Read access to the product details
            'automation:read': Read only access to automations
tags:
  - name: Automations
  - name: Automation Runs
  - name: Business Categories
  - name: Business Locations
  - name: Countries
  - name: Orders
  - name: Order Custom Fields
  - name: Partner Activatable Products
  - name: Partners
  - name: Products
  - name: Product Custom Fields
  - name: Proposals
  - name: Purchases
  - name: Sales Accounts
  - name: Sales Account Custom Fields
  - name: Sales Contacts
  - name: Subscription Assignments
  - name: Subscriptions
  - name: Users
  - name: User Custom Fields
  - name: Options
