openapi: 3.0.0
info:
  title: Platform REST APIs
  version: Evergreen
servers:
  - url: 'https://prod.apigateway.co/platform'
    description: Production
  - description: Demo
    url: 'https://demo.apigateway.co/platform'
  - description: Local
    url: '{local}/platform'
  - url: 'http://localhost:11001/platform'
    description: Localhost
paths:
  /salesContacts:
    post:
      summary: Create Sales Contact
      operationId: post-salesContacts
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Use this operation to create a new Sales Contact for a business.

        An email and business location must be provided when creating a contact.

        Note: Currently when creating a contact you must specify exactly 1 businessLocations id for it to be linked to. We intend to expand this limit.
      security:
        - OAuth:
            - sales.contact
      tags:
        - salesContacts
    options:
      operationId: options-salesContacts
      tags:
        - options
        - salesContacts
      summary: List valid HTTP verbs for /salesContacts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/salesContacts/{id}':
    get:
      summary: Get Sales Contact
      tags:
        - salesContacts
      operationId: get-salesContacts-id
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Fetch the current values for the specified sales contact
    options:
      operationId: options-salesContacts-id
      summary: 'List valid HTTP verbs for /salesContacts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - salesContacts
  '/salesContacts/{contactID}/locations':
    get:
      summary: List Locations related to the Sales Contact
      tags:
        - salesContacts
      operationId: get-salesContacts-contactID-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Returns a list of locations that are related to the Sales Contact
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-salesContacts-contactID-locations
      tags:
        - salesContacts
      summary: List valid HTTP verbs
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/salesContacts/{contactID}/relationships/locations':
    get:
      summary: List Location IDs related to Sales Contact
      operationId: get-salesContacts-contactID-relationships-locations
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Lists the IDs of the Business Locations that are related to this Sales Contact
      tags:
        - salesContacts
    post:
      summary: Add locations to Sales Contact
      operationId: post-salesContacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Adds the listed business locations to the specified sales contact. Locations that are already linked will be ignored.
      security:
        - OAuth:
            - sales.contact
      tags:
        - salesContacts
    patch:
      summary: Set Locations for Sales Contact
      operationId: patch-salesContacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Replaces all existing locations for the sales contact with the new list.

        Note: This can be completed as a single action with updating the contact's other attributes.
      tags:
        - salesContacts
      security:
        - OAuth:
            - sales.contact
    delete:
      summary: Remove locations from Sales Contact
      operationId: delete-salesContacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Removes the specified location(s) from the contact. Locations that have already been removed will be ignored.
      tags:
        - salesContacts
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-salesContacts-contactID-relationships-locations
      summary: 'List valid HTTP verbs for /salesContacts/{contactID}/relationships/locations'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - salesContacts
  /businessLocations:
    post:
      summary: Create Business Location
      operationId: post-businessLocations
      x-lifecycle:
        status: experimental
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
        - `relationships.categories.data.[].id` - At least one category must be provided
      security:
        - OAuth:
            - business
      tags:
        - businessLocations
    options:
      operationId: options-businessLocations
      summary: List valid HTTP verbs for /businessLocations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - businessLocations
  '/businessLocations/{id}':
    get:
      summary: Get Business Location
      tags:
        - businessLocations
      operationId: get-businessLocations-id
      x-lifecycle:
        status: experimental
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Returns basic data about the business location.
      security:
        - OAuth:
            - business
    options:
      operationId: options-businessLocations-id
      summary: 'List valid HTTP verbs for /businessLocations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - businessLocations
    patch:
      summary: Update Business Location
      operationId: patch-businessLocations-id
      tags:
        - businessLocations
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Update the existing business location. 
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: experimental
      security:
        - OAuth:
            - business
  '/partners/{id}':
    get:
      summary: Get Partner
      tags:
        - partners
      operationId: get-partners-id
      security:
        - OAuth:
            - partner
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Fetch the current values for the specified partner
    options:
      operationId: options-partners-id
      summary: 'List valid HTTP verbs for /partners/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - partners
  /invoices:
    get:
      summary: List Invoices
      tags:
        - invoices
      operationId: get-invoices
      security:
        - OAuth:
            - financial
      x-lifecycle:
        status: experimental
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Produces a list of invoices for wholesale fees
    options:
      operationId: options-invoices
      summary: 'List valid HTTP verbs for /invoices/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - invoices
  /businessCategories:
    get:
      summary: List Business Categories
      operationId: get-businessCategories
      tags:
        - businessCategories
      security:
        - OAuth:
            - business
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Produces a list of business categories
  /orders:
    post:
      summary: Create Order
      operationId: post-orders
      x-lifecycle:
        status: experimental
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Use this operation to create a new order for a business.
      security:
        - OAuth:
            - orders
      tags:
        - orders
  /orders/{id}:
    get:
      summary: Get Order
      tags:
        - orders
      operationId: get-orders-id
      security:
        - OAuth:
            - orders
      x-lifecycle:
        status: experimental
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Experimental`

        Fetch the current values for the specified order
    options:
      operationId: options-orders-id
      summary: 'List valid HTTP verbs for /orders/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - orders
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            business: Read-write access to business details
            partner: Read-write access to details about your partners
            financial: Read-write access to financial details
tags:
  - name: salesContacts
  - name: businessLocations
  - name: options
  - name: partners
  - name: invoices
  - name: businessCategories
  - name: orders
