openapi: 3.0.0
info:
  title: Platform REST APIs
  version: Evergreen
servers:
  - url: 'https://prod.apigateway.co/platform'
    description: Production
  - description: Demo
    url: 'https://demo.apigateway.co/platform'
  - description: Local
    url: '{local}/platform'
  - url: 'http://localhost:11001/platform'
    description: Localhost
paths:
  /contacts:
    post:
      summary: Create Contact
      operationId: post-contacts
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Use this operation to create a new Contact for a business.

        At least one of `name.first`, `name.last`, `phone.value` or `email` must be provided when creating a contact.
      security:
        - OAuth:
            - sales.contact
      tags:
        - contacts
    options:
      operationId: options-contacts
      tags:
        - options
        - contacts
      summary: List valid HTTP verbs for /contacts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/contacts/{id}':
    get:
      summary: Get Contact
      tags:
        - contacts
      operationId: get-contacts-id
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Fetch the current values for the specified contact
    options:
      operationId: options-contacts-id
      summary: 'List valid HTTP verbs for /contacts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - contacts
  '/contacts/{contactID}/locations':
    get:
      summary: List Locations related to Contact
      tags:
        - contacts
      operationId: get-contacts-contactID-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Returns a list of locations that are related to the contact
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-contacts-contactID-locations
      tags:
        - contacts
      summary: List valid HTTP verbs
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/contacts/{contactID}/relationships/locations':
    get:
      summary: List Location IDs related to Contact
      operationId: get-contacts-contactID-relationships-locations
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Lists the IDs of the Business Locations that are related to this Contact
      tags:
        - contacts
    post:
      summary: Add locations to contact
      operationId: post-contacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Adds the listed business locations to the specified contact. Locations that are already linked will be ignored.
      security:
        - OAuth:
            - sales.contact
      tags:
        - contacts
    patch:
      summary: Set Locations for Contact
      operationId: patch-contacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Replaces all existing locations for the contact with the new list.

        Note: This can be completed as a single action with updating the contact's other attributes.
      tags:
        - contacts
      security:
        - OAuth:
            - sales.contact
    delete:
      summary: Remove locations from contact
      operationId: delete-contacts-contactID-relationships-locations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Removes the specified location(s) from the contact. Locations that have already been removed will be ignored.
      tags:
        - contacts
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-contacts-contactID-relationships-locations
      summary: 'List valid HTTP verbs for /contacts/{contactID}/relationships/locations'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - contacts
  /businessLocations:
    post:
      summary: Create Business Location
      operationId: post-businessLocations
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
        - `relationships.categories.data.[].id` - At least one category must be provided
      security:
        - OAuth:
            - business
      tags:
        - businessLocations
    options:
      operationId: options-businessLocations
      summary: List valid HTTP verbs for /businessLocations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - businessLocations
  '/businessLocations/{id}':
    get:
      summary: Get Business Location
      tags:
        - businessLocations
      operationId: get-businessLocations-id
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Returns basic data about the business location.
      security:
        - OAuth:
            - business
    options:
      operationId: options-businessLocations-id
      summary: 'List valid HTTP verbs for /businessLocations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - businessLocations
  '/partners/{id}':
    get:
      summary: Get Partner
      tags:
        - partners
      operationId: get-partners-id
      security:
        - OAuth:
            - partner
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Fetch the current values for the specified partner
    options:
      operationId: options-partners-id
      summary: 'List valid HTTP verbs for /partners/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - partners
  /invoices:
    get:
      summary: List Payable Invoices
      tags:
        - invoices
      operationId: get-invoices
      security:
        - OAuth:
            - financial
      x-lifecycle:
        status: proposed
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Produces a list of invoices for wholesale fees
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            business: Read-write access to business details
            partner: Read-write access to details about your partners
            financial: Read-write access to financial details
tags:
  - name: contacts
  - name: businessLocations
  - name: options
  - name: partners
  - name: invoices
