openapi: 3.0.0
info:
  title: Platform REST APIs
  version: Evergreen
servers:
  - url: 'https://prod.apigateway.co/platform'
    description: Production
  - description: Demo
    url: 'https://demo.apigateway.co/platform'
  - description: Local
    url: '{local}/platform'
  - url: 'http://localhost:11001/platform'
    description: Localhost
paths:
  /salesContacts:
    post:
      summary: Create Sales Contact
      operationId: post-salesContacts
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Use this operation to create a new Sales Contact for a business.

        An email and business location must be provided when creating a contact.

        Note: Currently when creating a contact you must specify exactly 1 Business Location id for it to be linked to. We intend to expand this limit.
      security:
        - OAuth2:
            - sales.contact
      tags:
        - Sales Contacts
    options:
      operationId: options-salesContacts
      tags:
        - Options
        - Sales Contacts
      summary: List valid HTTP verbs for /salesContacts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/salesContacts/{id}':
    get:
      summary: Get Sales Contact
      tags:
        - Sales Contacts
      operationId: get-salesContacts-id
      security:
        - OAuth2:
            - sales.contact
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Fetch the current values for the specified sales contact
    options:
      operationId: options-salesContacts-id
      summary: 'List valid HTTP verbs for /salesContacts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Contacts
  /businessLocations:
    post:
      summary: Create Business Location
      operationId: post-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
        - `relationships.categories.data.[].id` - At least one category must be provided
      security:
        - OAuth2:
            - business
      tags:
        - Business Locations
    options:
      operationId: options-businessLocations
      summary: List valid HTTP verbs for /businessLocations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Locations
    get:
      summary: List Business Locations
      operationId: get-businessLocations
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of business locations
      security:
        - OAuth2:
            - business
      tags:
        - Business Locations
      x-lifecycle:
        status: trustedTester
  '/businessLocations/{id}':
    get:
      summary: Get Business Location
      tags:
        - Business Locations
      operationId: get-businessLocations-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns basic data about the business location.
      security:
        - OAuth2:
            - business
    options:
      operationId: options-businessLocations-id
      summary: 'List valid HTTP verbs for /businessLocations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Locations
    patch:
      summary: Update Business Location
      operationId: patch-businessLocations-id
      tags:
        - Business Locations
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update the existing business location.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2:
            - business
  /users:
    post:
      summary: Create User
      operationId: post-users
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.partner.data.id`
        - `attributes.email`
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
    options:
      operationId: options-users
      summary: List valid HTTP verbs for /users
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    get:
      summary: List Users
      operationId: get-users
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of users
      security:
        - OAuth2:
            - user.admin
            - user.list
      tags:
        - Users
      x-lifecycle:
        status: trustedTester
  '/users/{id}':
    get:
      summary: Get User
      tags:
        - Users
      operationId: get-users-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns information about a single user. The fields you are able to use will be affected by the combination of scopes that you were granted access to.
      security:
        - OAuth2:
            - user.admin
            - 'user.profile:read'
            - 'user.contact:read'
            - 'user.permission:read'
            - user.permission
            - self.user.admin
            - 'self.user.contact:read'
            - openid
            - profile
            - email
            - phone
            - address
    options:
      operationId: options-users-id
      summary: 'List valid HTTP verbs for /users/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    patch:
      summary: Update User
      operationId: patch-users-id
      tags:
        - Users
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Update the existing user.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: proposed
      security:
        - OAuth2:
            - user.admin
    delete:
      summary: Delete User
      operationId: delete-users-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Deleting a user will remove personal data from it and prevent the ID from being used again in the future.
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
      x-lifecycle:
        status: proposed
  /purchases:
    get:
      summary: List Purchases
      tags:
        - Purchases
      operationId: get-purchases
      security:
        - OAuth2:
            - financial
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of wholesale purchases made.
    options:
      operationId: options-purchases
      summary: List valid HTTP verbs for /purchases
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Purchases
  /businessCategories:
    get:
      summary: List Business Categories
      operationId: get-businessCategories
      tags:
        - Business Categories
      security:
        - OAuth2:
            - business
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of business categories
    options:
      operationId: options-businessCategories
      summary: List valid HTTP verbs for /businessCategories
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Business Categories
  /orders:
    post:
      summary: Create Order
      tags:
        - Orders
      operationId: post-orders
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Use this operation to create a new order for a business.
        All orders created by API start out in the `processing` status and do not require approval by either the partner admin or SMB admin.
      security:
        - OAuth2:
            - order
    options:
      operationId: options-orders
      summary: 'List valid HTTP verbs for /orders/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
    get:
      summary: List Orders
      operationId: get-orders
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of orders.
      security:
        - OAuth2:
            - order
      tags:
        - Orders
      x-lifecycle:
        status: trustedTester
  '/orders/{id}':
    get:
      summary: Get Order
      tags:
        - Orders
      operationId: get-orders-id
      security:
        - OAuth2:
            - order
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Fetch the current values for the specified order.
    options:
      operationId: options-order-id
      summary: 'List valid HTTP verbs for /orders/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Orders
  '/users/{id}/relationships/businessLocations':
    options:
      operationId: options-users-id-relationships-businessLocations
      summary: 'List valid HTTP verbs for ''/users/{id}/relationships/businessLocations'''
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Users
    post:
      summary: Associate user with location
      operationId: post-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Users can be granted access to business location(s) using the POST operation. After the operation completes, the user will have access to all their previous business locations plus any new locations in the POST request. If the user already has access to one or more of the specified locations they will be silently ignored.
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
    get:
      summary: Get user locations
      operationId: get-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Retrieves the business locations to which the User is associated.
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
    patch:
      summary: Replace user location access
      operationId: patch-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Users can be granted access to business location(s) or removed from access to business location(s) using the PATCH operation. After the operation completes, the user will have access only to those business locations specified in the request body (if any).
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
    delete:
      summary: Dissociate user from location
      operationId: delete-users-id-relationships-businessLocations
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Access to business locations can be removed from a user with the DELETE operation. If the user does not already have access to one or more of the specified locations, they will be silently ignored.
      security:
        - OAuth2:
            - user.admin
      tags:
        - Users
  /automationRuns:
    post:
      summary: Create automation run
      tags:
        - Automation Runs
      operationId: post-autoamtionruns
      security:
        - OAuth2:
            - business
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Create an automation run (to trigger a preconfigured automation)
    options:
      operationId: options-automationruns-id
      summary: List valid HTTP verbs for /automationRuns
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Automation Runs
  /salesAccounts:
    post:
      summary: Create Sales Account
      operationId: post-salesAccounts
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.businessPartner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
        - `relationships.categories.data.[].id` - At least one category must be provided
      security:
        - OAuth2:
            - sales.account
      tags:
        - Sales Accounts
    options:
      operationId: options-salesAccounts
      summary: List valid HTTP verbs for /salesAccounts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
    get:
      summary: List Sales Accounts
      operationId: get-salesAccounts
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Produces a list of sales accounts
      security:
        - OAuth2:
            - sales.account
      tags:
        - Sales Accounts
      x-lifecycle:
        status: trustedTester
  '/salesAccounts/{id}':
    get:
      summary: Get Sales Accounts
      operationId: get-salesAccounts-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns basic data about the sales account.
      security:
        - OAuth2:
            - sales.account
      tags:
        - Sales Accounts
    options:
      operationId: options-salesAccounts-by-id
      summary: 'List valid HTTP verbs for /salesAccounts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
    patch:
      summary: Update Sales Account
      operationId: patch-salesAccounts-by-id
      tags:
        - Sales Accounts
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Update the existing business location.
        Only the root ID and type fields are required. All others are optional and will keep their original value if omitted.
      x-lifecycle:
        status: trustedTester
      security:
        - OAuth2:
            - sales.account
  '/salesAccounts/{id}/relationships/customFields':
    get:
      summary: Get Custom Fields ID
      operationId: get-salesAccountCustomFieldsID-by-salesAccount
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Proposed`

        Returns a reference to the custom metadata for this sales account. Use the path without `/relationships/` in it to get the actual data.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2:
            - sales.account
      x-lifecycle:
        status: proposed
      tags:
        - Sales Accounts
    options:
      summary: ''
      operationId: options-salesAccountCustomFieldsID-by-salesAccount
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
  '/salesAccounts/{id}/customFields':
    get:
      summary: Get Custom Fields
      operationId: get-salesAccountCustomFields-by-salesAccount
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        This endpoint acts like a alias to [Get Sales Account Custom Fields by ID endpoint](b3A6MzYxMTM5MTY-get-sales-account-custom-data-by-id). It returns custom fields about a sales account.
      security:
        - OAuth2:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Sales Accounts
    options:
      summary: ''
      operationId: options-salesAccountCustomFields-by-salesAccount
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Accounts
  '/salesAccountCustomFields/{id}':
    patch:
      summary: Update Custom Fields
      operationId: patch-salesAccountCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to a Sales Account
      security:
        - OAuth2:
            - sales.account
      tags:
        - Sales Account Custom Fields
    get:
      summary: Get Custom Fields by ID
      operationId: get-salesAccountCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields about a sales account.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2:
            - sales.account
      x-lifecycle:
        status: trustedTester
      tags:
        - Sales Account Custom Fields
    options:
      summary: ''
      operationId: options-salesAccountCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - Sales Account Custom Fields
  '/users/{id}/customFields':
    get:
      summary: Get Custom Fields
      operationId: get-userCustomFields-by-userid
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        This endpoint acts like a alias to [Get User Custom Fields by ID endpoint](b3A6MzczMDUyMjU-get-custom-fields-by-id). It returns custom fields for a user.
      security:
        - OAuth2:
            - user.admin
      x-lifecycle:
        status: trustedTester
      tags:
        - Users
    options:
      summary: 'List valid HTTP verbs for /users/{id}/customFields'
      operationId: options-userCustomFields-by-userid
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - User Custom Fields

  '/userCustomFields/{id}':
    patch:
      summary: Update Custom Fields
      operationId: patch-userCustomFields-by-id
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Custom Fields are an additional information attached to a User
      security:
        - OAuth2:
            - user.admin
      tags:
        - User Custom Fields
    get:
      summary: Get Custom Fields by ID
      operationId: get-userCustomFields-by-id
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`

        Returns custom fields about a user.

        Attributes can be set up at the partner administration page in Partner Center.
      security:
        - OAuth2:
            - user.admin
      x-lifecycle:
        status: trustedTester
      tags:
        - User Custom Fields
    options:
      summary: ''
      operationId: options-userCustomFields-by-id
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - Options
        - User Custom Fields
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            business: Read-write access to business details
            partner: Read-write access to details about your partner
            financial: Read-write access to financial details
            order: Read-write access to order details
            'user.profile:read': Read access to the profile fields of all categories of users
            'user.contact:read': 'Read access to the contact info (email, phone, address) of all categories of users'
            'user.permission:read': 'Read access to the permission info (accessible locations, features and roles) of all categories of users'
            user.permission: 'Read-write access to the permission info (accessible locations, features and roles) of all categories of users'
            user.admin: Read-write access to manage all users
            user.list: '''Allows searching for users based on a set of filters. (ex: email, name, category, organization). Without this scope an exact user id is required.'
            self.user.admin: 'Allows editing the profile, contact info and profile image for the current user.'
            'self.user.contact:read': 'Read access to the contact info (email, phone, address) of the current user.'
            openid: Allows getting the user id of the current user
            profile: 'Readonly access to the user profile, including name, locale, and language preferences.'
            email: Allows readonly access to the email of the current user.
            phone: Allows readonly access to the phone numbers of the current user.
            address: Allows readonly access to the address of the current user.
            sales.account: Allows read-write access to account records
tags:
  - name: Automation Runs
  - name: Business Categories
  - name: Business Locations
  - name: Users
  - name: Sales Contacts
  - name: Sales Accounts
  - name: Sales Account Custom Fields
  - name: User Custom Fields
  - name: Purchases
  - name: Orders
  - name: Partners
  - name: Options
