openapi: 3.0.0
info:
  title: Platform REST APIs
  version: Evergreen
servers:
  - url: 'https://prod.apigateway.co/platform'
    description: Production
  - description: Demo
    url: 'https://demo.apigateway.co/platform'
  - description: Local
    url: '{local}/platform'
  - url: 'https://vendasta.stoplight.io/mocks/vendasta/openapi-specs/1808816'
    description: Mock
  - url: 'http://localhost:11001/platform'
    description: Localhost
paths:
  /accountContacts:
    post:
      summary: Create Account Contact
      operationId: post-accountContacts
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`

        Use this operation to create a new Contact for an account.

        At least one of `name.first`, `name.last`, `phone.raw` or `email` must be provided when creating a contact.
      security:
        - OAuth:
            - sales.contact
      tags:
        - accountContacts
    options:
      operationId: options-accountContacts
      tags:
        - options
        - accountContacts
      summary: List valid HTTP verbs for /accountContacts
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/accountContacts/{id}':
    get:
      summary: Get Account Contact
      tags:
        - accountContacts
      operationId: get-accountContacts-id
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Fetch the current values for the specified account contact
    options:
      operationId: options-accountContacts-id
      summary: 'List valid HTTP verbs for /accountContacts/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - accountContacts
  '/accountContacts/{contactID}/locations':
    get:
      summary: List Locations related to Contact
      tags:
        - accountContacts
      operationId: get-accountContacts-contactID-locations
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Returns a list of locations that are related to the contact
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-accountContacts-contactID-locations
      tags:
        - accountContacts
      summary: List valid HTTP verbs
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
  '/accountContacts/{contactID}/relationships/locations':
    get:
      summary: List Location IDs related to Contact
      operationId: get-accountContacts-contactID-relationships-locations
      security:
        - OAuth:
            - sales.contact
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Lists the IDs of the Account Locations that are related to this Account Contact
      tags:
        - accountContacts
    post:
      summary: Add locations to contact
      operationId: post-accountContacts-contactID-relationships-locations
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Adds the listed account locations to the specified account contact. Locations that are already linked will be ignored. 
      security:
        - OAuth:
            - sales.contact
      tags:
        - accountContacts
    patch:
      summary: Set Locations for Contact
      operationId: patch-accountContacts-contactID-relationships-locations
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Replaces all existing locations for the contact with the new list.

        Note: This can be completed as a single action with updating the contact's other attributes.
      tags:
        - accountContacts
      security:
        - OAuth:
            - sales.contact
    delete:
      summary: Remove locations from contact
      operationId: delete-accountContacts-contactID-relationships-locations
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Removes the specified location(s) from the contact. Locations that have already been removed will be ignored.
      tags:
        - accountContacts
      security:
        - OAuth:
            - sales.contact
    options:
      operationId: options-accountContacts-contactID-relationships-locations
      summary: 'List valid HTTP verbs for /accountContacts/{contactID}/relationships/locations'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - accountContacts
  /accountLocations:
    post:
      summary: Create Account Location
      operationId: post-accountLocations
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Used to record basic data for a new location.

        The following members must be populated during creation:
        - `relationships.owner.data.id`
        - `attributes.name`
        - `attributes.address.countryCode` as well as other address fields based on the norms of the country.
        - `relationships.categories.data.[].id` - At least one category must be provided
      security:
        - OAuth:
            - account
      tags:
        - accountLocations
    options:
      operationId: options-accountLocations
      summary: List valid HTTP verbs for /accountLocations
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - accountLocations
  '/accountLocations/{id}':
    get:
      summary: Get Account Location
      tags:
        - accountLocations
      operationId: get-accountLocations-id
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Returns basic data about the account location.
      security:
        - OAuth:
            - account
    options:
      operationId: options-accountLocations-id
      summary: 'List valid HTTP verbs for /accountLocations/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - accountLocations
  '/partners/{id}':
    get:
      summary: Get Partner
      tags:
        - partners
      operationId: get-partners-id
      security:
        - OAuth:
            - partner
      x-lifecycle:
        status: "proposed"
      description: |-
        [Status](https://vendasta.stoplight.io/docs/openapi-specs/docs/1.-Overview/Versioning.md): `Proposed`
        
        Fetch the current values for the specified partner
    options:
      operationId: options-partners-id
      summary: 'List valid HTTP verbs for /partners/{id}'
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      tags:
        - options
        - partners
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            sales.contact: Read-write access to sales contact details
            account: Read-write access to account details
            partner: Read-write access to details about your partners
tags:
  - name: accountContacts
  - name: accountLocations
  - name: options
  - name: partners
