swagger: "2.0"
info:
  title: telephony/v1/api.proto
  version: version not set
tags:
  - name: Fuze
  - name: Telephony
consumes:
  - application/json
produces:
  - application/json
paths:
  /telephony.v1.Fuze/GetPartnerConfigs:
    post:
      summary: Handles the getting of Telephony partner configs
      operationId: Fuze_GetPartnerConfigs
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetPartnerConfigsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetPartnerConfigsRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/GetUserConfigs:
    post:
      summary: Handles getting TelephonyUser Configs
      operationId: Fuze_GetUserConfigs
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetUserConfigsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetUserConfigsRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/OffboardPartner:
    post:
      summary: handles offboarding a Fuze partner, sets the Deleted timestamp
      operationId: Fuze_OffboardPartner
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OffboardFuzePartnerResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1OffboardFuzePartnerRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/OffboardUser:
    post:
      summary: Handles the offboarding of a Fuze User
      operationId: Fuze_OffboardUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OffboardFuzeUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1OffboardFuzeUserRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/OnboardPartner:
    post:
      summary: Handles the initial Fuze configuration of a Partner
      operationId: Fuze_OnboardPartner
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OnboardFuzePartnerResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1OnboardFuzePartnerRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/OnboardUser:
    post:
      summary: Handles the initial Fuze configuration of a User by phone number
      operationId: Fuze_OnboardUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OnboardFuzeUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1OnboardFuzeUserRequest'
      tags:
        - Fuze
  /telephony.v1.Fuze/OnboardUserV2:
    post:
      summary: Handles the initial Fuze configuration of a User by userName
      operationId: Fuze_OnboardUserV2
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OnboardFuzeUserV2Response'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1OnboardFuzeUserV2Request'
      tags:
        - Fuze
  /telephony.v1.Telephony/ClickToCall:
    post:
      summary: Handles click-to-call functionality
      operationId: Telephony_ClickToCall
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ClickToCallResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ClickToCallRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/DeleteFromBucket:
    post:
      operationId: Telephony_DeleteFromBucket
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DeleteFromBucketResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeleteFromBucketRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/GetFileNamesByAccountGroupID:
    post:
      operationId: Telephony_GetFileNamesByAccountGroupID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetFileNamesByAccountGroupIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetFileNamesByAccountGroupIDRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/GetFileNamesByContactID:
    post:
      operationId: Telephony_GetFileNamesByContactID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetFileNamesByContactIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetFileNamesByContactIDRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/GetFileNamesByIamID:
    post:
      operationId: Telephony_GetFileNamesByIamID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetFileNamesByIamIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetFileNamesByIamIDRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/GetFileNamesByPartnerID:
    post:
      operationId: Telephony_GetFileNamesByPartnerID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetFileNamesByPartnerIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetFileNamesByPartnerIDRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/GetRecordingURLByFilename:
    post:
      operationId: Telephony_GetRecordingURLByFilename
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetRecordingURLByFilenameResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetRecordingURLByFilenameRequest'
      tags:
        - Telephony
  /telephony.v1.Telephony/TransferToBucket:
    post:
      operationId: Telephony_TransferToBucket
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1TransferToBucketResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1TransferToBucketRequest'
      tags:
        - Telephony
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1ClickToCallRequest:
    type: object
    properties:
      partnerId:
        type: string
      iamUserId:
        type: string
      targetPhoneNumber:
        type: string
  v1ClickToCallResponse:
    type: object
  v1DeleteFromBucketRequest:
    type: object
    properties:
      fileName:
        type: string
  v1DeleteFromBucketResponse:
    type: object
  v1FuzeUserConfig:
    type: object
    properties:
      fuzeUserId:
        type: string
      allowUserRecordings:
        type: boolean
      fuzePhoneNumber:
        type: string
      fuzeUserName:
        type: string
  v1GetFileNamesByAccountGroupIDRequest:
    type: object
    properties:
      accountGroupId:
        type: string
  v1GetFileNamesByAccountGroupIDResponse:
    type: object
    properties:
      fileNames:
        type: array
        items:
          type: string
  v1GetFileNamesByContactIDRequest:
    type: object
    properties:
      contactId:
        type: string
  v1GetFileNamesByContactIDResponse:
    type: object
    properties:
      fileNames:
        type: array
        items:
          type: string
  v1GetFileNamesByIamIDRequest:
    type: object
    properties:
      iamId:
        type: string
  v1GetFileNamesByIamIDResponse:
    type: object
    properties:
      fileNames:
        type: array
        items:
          type: string
  v1GetFileNamesByPartnerIDRequest:
    type: object
    properties:
      parntnerId:
        type: string
  v1GetFileNamesByPartnerIDResponse:
    type: object
    properties:
      fileNames:
        type: array
        items:
          type: string
  v1GetPartnerConfigsRequest:
    type: object
    properties:
      partnerId:
        type: string
  v1GetPartnerConfigsResponse:
    type: object
    properties:
      fuzeConfig:
        $ref: '#/definitions/v1PartnerFuzeConfig'
    title: Additional service configs should be added here
  v1GetRecordingURLByFilenameRequest:
    type: object
    properties:
      filename:
        type: string
  v1GetRecordingURLByFilenameResponse:
    type: object
    properties:
      redirectUrl:
        type: string
      timeToExpire:
        type: string
        format: int64
  v1GetUserConfigsRequest:
    type: object
    properties:
      partnerId:
        type: string
      iamUserId:
        type: string
  v1GetUserConfigsResponse:
    type: object
    properties:
      fuzeUserConfigs:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1FuzeUserConfig'
  v1OffboardFuzePartnerRequest:
    type: object
    properties:
      partnerId:
        type: string
  v1OffboardFuzePartnerResponse:
    type: object
  v1OffboardFuzeUserRequest:
    type: object
    properties:
      partnerId:
        type: string
      iamUserId:
        type: string
  v1OffboardFuzeUserResponse:
    type: object
    properties:
      response:
        $ref: '#/definitions/v1UserOffboardResponse'
      values:
        $ref: '#/definitions/v1OffboardFuzeUserRequest'
  v1OnboardFuzePartnerRequest:
    type: object
    properties:
      partnerId:
        type: string
      fuzeWardenAuthToken:
        type: string
      allowRecordings:
        type: boolean
      minLengthForAnsweredCall:
        type: string
        format: int64
      logUnansweredCalls:
        type: boolean
      recordingRetentionDays:
        type: string
        format: int64
  v1OnboardFuzePartnerResponse:
    type: object
  v1OnboardFuzeUserRequest:
    type: object
    properties:
      partnerId:
        type: string
      iamUserId:
        type: string
      fuzePhoneNumber:
        type: string
      allowRecordings:
        type: boolean
  v1OnboardFuzeUserResponse:
    type: object
    properties:
      response:
        $ref: '#/definitions/v1UserResponse'
      values:
        $ref: '#/definitions/v1OnboardFuzeUserRequest'
  v1OnboardFuzeUserV2Request:
    type: object
    properties:
      partnerId:
        type: string
      iamUserId:
        type: string
      fuzeUserName:
        type: string
      allowRecordings:
        type: boolean
  v1OnboardFuzeUserV2Response:
    type: object
    properties:
      response:
        $ref: '#/definitions/v1UserResponse'
      values:
        $ref: '#/definitions/v1OnboardFuzeUserV2Request'
  v1PartnerFuzeConfig:
    type: object
    properties:
      isAuthTokenSaved:
        type: boolean
      allowRecordings:
        type: boolean
      minLengthForAnsweredCalls:
        type: string
        format: int64
      logUnansweredCalls:
        type: boolean
  v1TransferToBucketRequest:
    type: object
    properties:
      sourceUrl:
        type: string
      providerType:
        type: string
      partnerId:
        type: string
      iamUserId:
        type: string
      accountGroupId:
        type: string
      contactId:
        type: string
      callDateTime:
        type: string
        format: date-time
      callDuration:
        type: string
        format: int64
      recordingRetentionDays:
        type: string
        format: int64
  v1TransferToBucketResponse:
    type: object
    properties:
      fileName:
        type: string
  v1UserOffboardResponse:
    type: string
    enum:
      - USER_OFFBOARD_RESPONSE_INVALID
      - USER_OFFBOARD_RESPONSE_SUCCESS
    default: USER_OFFBOARD_RESPONSE_INVALID
  v1UserResponse:
    type: string
    enum:
      - USER_RESPONSE_INVALID
      - USER_RESPONSE_SUCCESS
      - USER_RESPONSE_PID_NOT_FUZE
      - USER_RESPONSE_USER_DOES_NOT_EXIST
      - USER_RESPONSE_OTHER_ERROR
    default: USER_RESPONSE_INVALID
