swagger: "2.0"
info:
  title: sms/v1/api.proto
  version: version not set
tags:
  - name: SmsService
  - name: ConversationService
  - name: Twilio
consumes:
  - application/json
produces:
  - application/json
paths:
  /sms.v1.ConversationService/GetMessage:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_GetMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMessageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMessageRequest'
      tags:
        - ConversationService
  /sms.v1.ConversationService/GetMultiMessages:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_GetMultiMessages
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMultiMessagesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMultiMessagesRequest'
      tags:
        - ConversationService
  /sms.v1.ConversationService/ListConversations:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_ListConversations
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListConversationsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListConversationsRequest'
      tags:
        - ConversationService
  /sms.v1.ConversationService/ListMessages:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_ListMessages
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListMessagesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListMessagesRequest'
      tags:
        - ConversationService
  /sms.v1.ConversationService/SendMessage:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_SendMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SendMessageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SendMessageRequest'
      tags:
        - ConversationService
  /sms.v1.ConversationService/SendSMS:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: ConversationService_SendSMS
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SendSMSResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SendSMSRequest'
      tags:
        - ConversationService
  /sms.v1.SmsService/CreateSmsClickedEvent:
    post:
      summary: |-
        creates an SMS clicked event
        this is the only thing that isn't deprecated
      operationId: SmsService_CreateSmsClickedEvent
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateSmsClickedEventRequest'
      tags:
        - SmsService
  /sms.v1.SmsService/GetAccountInfo:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: SmsService_GetAccountInfo
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAccountInfoResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAccountInfoRequest'
      tags:
        - SmsService
  /sms.v1.Twilio/StartTrustHubRegistration:
    post:
      summary: 'Deprecated: use V2 APIs'
      operationId: Twilio_StartTrustHubRegistration
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1StartTrustHubRegistrationRequest'
      tags:
        - Twilio
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  smsv1Status:
    type: string
    enum:
      - STATUS_NONE
      - STATUS_SENT
      - STATUS_DELIVERED
      - STATUS_READ
      - STATUS_FAILED
      - STATUS_UNDELIVERED
    default: STATUS_NONE
    title: Status represents the status of a message
  v1Attribute:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
    title: A key/value attribute
  v1ChannelType:
    type: string
    enum:
      - CHANNEL_TYPE_UNKNOWN
      - CHANNEL_TYPE_CHAT
      - CHANNEL_TYPE_SMS
    default: CHANNEL_TYPE_UNKNOWN
    title: ChannelType represent the channel types of messages
  v1Conversation:
    type: object
    properties:
      senderId:
        type: string
        title: The id of sender
      recipientId:
        type: string
        title: The id of recipient
      partnerId:
        type: string
        title: The partner that the conversation belongs to
      conversationId:
        type: string
        title: The unique id of the conversation
      participantIds:
        type: array
        items:
          type: string
        title: The id of participants
      created:
        type: string
        format: date-time
        title: Time when the conversation was created
      updated:
        type: string
        format: date-time
        title: Time when the conversation was updated
      deleted:
        type: string
        format: date-time
        title: Time when the conversation was deleted
    title: Conversation represents an conversation model
  v1ConversationMessages:
    type: object
    properties:
      conversationId:
        type: string
        title: The id of the conversation
      messages:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Message'
        title: The list of the message's ids
  v1CreateSmsClickedEventRequest:
    type: object
    properties:
      messageUuid:
        type: string
        title: Unique id to associate to a particular message_sid
    title: Request to create an SMS clicked event
  v1ErrorCode:
    type: string
    enum:
      - ERROR_CODE_NONE
    default: ERROR_CODE_NONE
    title: ErrorCode represents the error code of a message
  v1GetAccountInfoRequest:
    type: object
    properties:
      sender:
        $ref: '#/definitions/v1Participant'
        title: The sender to get sms info about
    title: Request to get info about an sms account
  v1GetAccountInfoResponse:
    type: object
    properties:
      phoneNumber:
        type: string
    title: Response with info about an sms account
  v1GetMessageRequest:
    type: object
    properties:
      sender:
        $ref: '#/definitions/v1Participant'
        title: The business or account group id of the conversation
      conversationId:
        type: string
        title: The id of the conversation
      messageId:
        type: string
        title: The id of the message
    title: Request to get a message
  v1GetMessageResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/v1Message'
    title: Response to a request to get a message
  v1GetMultiMessagesRequest:
    type: object
    properties:
      sender:
        $ref: '#/definitions/v1Participant'
        title: The business or account group id of the conversation
      messageKeys:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1MessageKey'
        title: The messageKeys of the conversation
    title: Request to get multi messages
  v1GetMultiMessagesResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ConversationMessages'
    title: Response to a request to get multi messages for multi conversations
  v1ListConversationsRequest:
    type: object
    properties:
      senderId:
        type: string
        title: sender id that the conversations are list for
      cursor:
        type: string
        title: current cursor position
      pageSize:
        type: string
        format: int64
        title: |-
          size of the page to list
          0 assumes the default page size
    title: Request to get a list of conversations
  v1ListConversationsResponse:
    type: object
    properties:
      conversations:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Conversation'
        title: list of the requested conversation data
      nextCursor:
        type: string
        title: A cursor that can be provided to retrieve the next page of results
      hasMore:
        type: boolean
        title: Whether or not more results exist
    title: Response to a request to get a list of conversations
  v1ListMessagesRequest:
    type: object
    properties:
      senderId:
        type: string
        title: The sender id of the conversation
      recipientId:
        type: string
        title: The recipient id of the conversation
      cursor:
        type: string
        title: The cursor from which to list
      pageSize:
        type: string
        format: int64
        title: The page size of the list
    title: Request to get a list of messages
  v1ListMessagesResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Message'
        title: The page of listed messages
      nextCursor:
        type: string
        title: The cursor for the next page
      hasMore:
        type: boolean
        title: Whether there is another page
    title: Response to a request to get a list of messages
  v1Message:
    type: object
    properties:
      conversationId:
        type: string
        title: The id of the conversation
      messageId:
        type: string
        title: The id of the message
      channelType:
        $ref: '#/definitions/v1ChannelType'
        title: The type of channel
      participant:
        $ref: '#/definitions/v1Participant'
        title: The participant of the message
      body:
        type: string
        title: The body of the message
      status:
        $ref: '#/definitions/smsv1Status'
        title: The status of the message
      errorCode:
        $ref: '#/definitions/v1ErrorCode'
        title: The error code of the message
      removed:
        type: string
        format: date-time
        title: The removed time of the message
      created:
        type: string
        format: date-time
        title: The created time of the message
      updated:
        type: string
        format: date-time
        title: The updated time of the message
      deleted:
        type: string
        format: date-time
        title: The deleted time of the message
      media:
        type: string
        title: A json encoded string of the media on a message
    title: Message represents a conversation message model
  v1MessageKey:
    type: object
    properties:
      conversationId:
        type: string
        title: The id of the conversation
      messageIds:
        type: array
        items:
          type: string
        title: The list of the message's ids
  v1Participant:
    type: object
    properties:
      internalId:
        type: string
        title: ID in our system for the sender (e.g. account group ID)
      type:
        $ref: '#/definitions/v1ParticipantType'
        title: The participant's type in our system (e.g. account group)
  v1ParticipantType:
    type: string
    enum:
      - PARTICIPANT_TYPE_UNKNOWN
      - PARTICIPANT_TYPE_ACCOUNT_GROUP
      - PARTICIPANT_TYPE_CUSTOMER
    default: PARTICIPANT_TYPE_UNKNOWN
  v1SendMessageRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        title: The account group id
      conversationId:
        type: string
        title: The conversation external id
      recipientPhoneNumber:
        type: string
        title: Phone number of the recipient
      messageBody:
        type: string
        title: The message body
    title: Request to send a Message in a conversation
  v1SendMessageResponse:
    type: object
    properties:
      messageId:
        type: string
        title: The message external id
      conversationId:
        type: string
        title: The conversation external id
    title: Response of a message sent in a conversation
  v1SendSMSRequest:
    type: object
    properties:
      sender:
        $ref: '#/definitions/v1Participant'
        title: Participant representing the sender
      recipient:
        $ref: '#/definitions/v1Participant'
        title: Participant representing the recipient
      recipientPhoneNumber:
        type: string
        title: Phone number of the recipient
      messageToSend:
        type: string
        title: The message to send
      partnerId:
        type: string
        title: Partner ID associated with sender
      attributes:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Attribute'
        title: Any number of attributes to attach to the sms message
      origin:
        type: string
        title: Vendor ID of the product where this message originated. May be blank if sent from VBC
    title: Request to send an SMS in a conversation
  v1SendSMSResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/v1Message'
    title: Response to send an SMS in a conversation
  v1StartTrustHubRegistrationRequest:
    type: object
    properties:
      accountGroupId:
        type: string
        title: the account group to register with Twilio
