swagger: "2.0"
info:
  title: wordfence/v1/api.proto
  version: version not set
tags:
  - name: Entity
  - name: Website
  - name: Report
consumes:
  - application/json
produces:
  - application/json
paths:
  /wordfence.v1.Entity/ListPluginVulnerabilities:
    post:
      summary: ListPluginVulnerabilities returns a list of vulnerabilities for a given plugin slug and version.
      operationId: Entity_ListPluginVulnerabilities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListPluginVulnerabilitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListPluginVulnerabilitiesRequest'
      tags:
        - Entity
  /wordfence.v1.Entity/ListThemeVulnerabilities:
    post:
      summary: ListThemeVulnerabilities returns a list of vulnerabilities for a given theme slug and version.
      operationId: Entity_ListThemeVulnerabilities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListThemeVulnerabilitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListThemeVulnerabilitiesRequest'
      tags:
        - Entity
  /wordfence.v1.Entity/ListWordpressVulnerabilities:
    post:
      summary: ListWordpressVulnerabilities returns a list of vulnerabilities for a given WordPress version.
      operationId: Entity_ListWordpressVulnerabilities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListWordpressVulnerabilitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListWordpressVulnerabilitiesRequest'
      tags:
        - Entity
  /wordfence.v1.Report/GetMarketingServicesReport:
    post:
      summary: GetMarketingServicesReport returns vulnerability data for all websites managed by marketing services.
      operationId: Report_GetMarketingServicesReport
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMarketingServicesReportResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMarketingServicesReportRequest'
      tags:
        - Report
  /wordfence.v1.Report/GetPartnerReport:
    post:
      summary: GetPartnerReport returns vulnerability data for all websites managed by given partner.
      operationId: Report_GetPartnerReport
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetPartnerReportResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetPartnerReportRequest'
      tags:
        - Report
  /wordfence.v1.Website/GetMultiWebsiteVulnerabilities:
    post:
      summary: GetMultiWebsiteVulnerabilities returns a list of vulnerabilities for a given list of websites.
      operationId: Website_GetMultiWebsiteVulnerabilities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMultiWebsiteVulnerabilitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMultiWebsiteVulnerabilitiesRequest'
      tags:
        - Website
  /wordfence.v1.Website/GetWebsiteVulnerabilities:
    post:
      summary: GetWebsiteVulnerabilities returns a list of vulnerabilities for a given website.
      operationId: Website_GetWebsiteVulnerabilities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetWebsiteVulnerabilitiesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetWebsiteVulnerabilitiesRequest'
      tags:
        - Website
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GetMarketingServicesReportRequest:
    type: object
    properties:
      page:
        type: string
        format: int64
      filters:
        $ref: '#/definitions/v1MarketingServicesReportFilters'
  v1GetMarketingServicesReportResponse:
    type: object
    properties:
      siteData:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ReportSiteData'
  v1GetMultiWebsiteVulnerabilitiesRequest:
    type: object
    properties:
      websiteIds:
        type: array
        items:
          type: string
  v1GetMultiWebsiteVulnerabilitiesResponse:
    type: object
    properties:
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1WebsiteVulnerabilities'
  v1GetPartnerReportRequest:
    type: object
    properties:
      partnerId:
        type: string
      page:
        type: string
        format: int64
      filters:
        $ref: '#/definitions/v1PartnerReportFilters'
  v1GetPartnerReportResponse:
    type: object
    properties:
      siteData:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ReportSiteData'
  v1GetWebsiteVulnerabilitiesRequest:
    type: object
    properties:
      websiteId:
        type: string
  v1GetWebsiteVulnerabilitiesResponse:
    type: object
    properties:
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
  v1ListPluginVulnerabilitiesRequest:
    type: object
    properties:
      pluginSlug:
        type: string
      pluginVersion:
        type: string
  v1ListPluginVulnerabilitiesResponse:
    type: object
    properties:
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
  v1ListThemeVulnerabilitiesRequest:
    type: object
    properties:
      themeSlug:
        type: string
      themeVersion:
        type: string
  v1ListThemeVulnerabilitiesResponse:
    type: object
    properties:
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
  v1ListWordpressVulnerabilitiesRequest:
    type: object
    properties:
      wordpressVersion:
        type: string
  v1ListWordpressVulnerabilitiesResponse:
    type: object
    properties:
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
  v1MarketingServicesReportFilters:
    type: object
    properties:
      partnerId:
        type: string
      companyName:
        type: string
  v1PartnerReportFilters:
    type: object
    properties:
      searchTerm:
        type: string
  v1ReportSiteData:
    type: object
    properties:
      websiteId:
        type: string
      partnerId:
        type: string
      accountGroupId:
        type: string
      companyName:
        type: string
      websiteUrl:
        type: string
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
  v1Vulnerability:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      slug:
        type: string
      affectedVersions:
        type: array
        items:
          type: string
      patched:
        type: boolean
      patchedVersions:
        type: array
        items:
          type: string
      informational:
        type: boolean
      title:
        type: string
      description:
        type: string
      remediation:
        type: string
      cvssScore:
        type: number
        format: float
      cvssRating:
        type: string
      cve:
        type: string
      cveLink:
        type: string
      publishedAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
  v1WebsiteVulnerabilities:
    type: object
    properties:
      websiteId:
        type: string
      vulnerabilities:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Vulnerability'
