openapi: 3.0.0
info:
  description: Endpoints used to aid in operating the API Gateway
  title: API Context
  termsOfService: 'https://vendasta.com/terms'
  contact:
    email: api@vendasta.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: Evergreen
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/errorCodes/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
    get:
      summary: Get Error Code
      tags:
        - api-errorCode
      responses: {}
      operationId: get-apiErrorCodes
      description: ''
components:
  schemas: {}
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          scopes:
            terms.write: write terms
            finance.partners.read: read partners
            hr.employees.read: read employees
            hr.teams.read: read teams
            hr.roles.read: read roles
            hr.roles.write: write roles
            crm.customers.read: read customers
            crm.customers.write: write customers
            crm.contacts.read: read contacts
            crm.contacts.write: write contacts
            sales.leads.read: read leads
            sales.opportunities.read: read opportunities
            sales.orders.read: read orders
            product.products.read: read products
            product.packages.read: read packages
