swagger: "2.0"
info:
  title: notifications/v1/legacy/legacy.proto
  version: version not set
tags:
  - name: LegacyNotificationPreference
consumes:
  - application/json
produces:
  - application/json
paths:
  /notifications.v1.legacy.LegacyNotificationPreference/BulkUpdate:
    post:
      operationId: LegacyNotificationPreference_BulkUpdate
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyBulkUpdateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyBulkUpdateRequest'
      tags:
        - LegacyNotificationPreference
  /notifications.v1.legacy.LegacyNotificationPreference/Delete:
    post:
      operationId: LegacyNotificationPreference_Delete
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyDeleteResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyDeleteRequest'
      tags:
        - LegacyNotificationPreference
  /notifications.v1.legacy.LegacyNotificationPreference/Get:
    post:
      operationId: LegacyNotificationPreference_Get
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyGetResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyGetRequest'
      tags:
        - LegacyNotificationPreference
  /notifications.v1.legacy.LegacyNotificationPreference/GetAvailableSections:
    post:
      summary: proxy to /nsInternalApi/v3/notificationSettings/getAvailableSections/
      operationId: LegacyNotificationPreference_GetAvailableSections
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyGetAvailableSectionsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyGetAvailableSectionsRequest'
      tags:
        - LegacyNotificationPreference
  /notifications.v1.legacy.LegacyNotificationPreference/List:
    post:
      operationId: LegacyNotificationPreference_List
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyListResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyListRequest'
      tags:
        - LegacyNotificationPreference
  /notifications.v1.legacy.LegacyNotificationPreference/Update:
    post:
      operationId: LegacyNotificationPreference_Update
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/legacyUpdateResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/legacyUpdateRequest'
      tags:
        - LegacyNotificationPreference
definitions:
  BulkUpdateRequestByIdentifier:
    type: object
    properties:
      identifiers:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyIdentifier'
    title: A list of explicit identifiers for use in selection.preference_by_identifiers
  BulkUpdateRequestByPartner:
    type: object
    properties:
      partnerId:
        type: string
    title: A partner id for actions across an entire pid
  BulkUpdateRequestByUser:
    type: object
    properties:
      partnerId:
        type: string
      userIds:
        type: array
        items:
          type: string
    title: A list of users for use in selection.business_by_user
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  legacyBulkUpdateRequest:
    type: object
    properties:
      changes:
        $ref: '#/definitions/legacyPreference'
        description: changes represents all of the changes that wish to be applied. The identifier on the preference is ignored.
      preferenceByIdentifiers:
        $ref: '#/definitions/BulkUpdateRequestByIdentifier'
        title: Updates the specified preferences by exact reference
      businessByUser:
        $ref: '#/definitions/BulkUpdateRequestByUser'
        title: business_by_user updates all business associated with each user
      businessByPartner:
        $ref: '#/definitions/BulkUpdateRequestByPartner'
        title: business_by_partner updates all businesses on a partner
      userByPartner:
        $ref: '#/definitions/BulkUpdateRequestByPartner'
        title: user_by_partner updates all smb users on a partner
      identifiers:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyIdentifier'
        title: 'Deprecated: use selection preference_by_identifiers'
      partialIdentifiers:
        type: boolean
        description: |-
          Deprecated: use selection business_by_user
          partial_identifiers indicates that the included identifiers are incomplete and the operation should be applied to those underneath them in the hierarchy.
          e.g. the provided identifiers are for a user, but the update should be applied to every account group that the user is associated with.
  legacyBulkUpdateResponse:
    type: object
    properties:
      progressToken:
        type: string
        description: |-
          Progress token is a string that can be used to track the progress of any asynchronous work, likely a workflow ID.
          The absence of a returned token should indicate that the work has completed synchronously.
  legacyDeleteRequest:
    type: object
    properties:
      identifier:
        $ref: '#/definitions/legacyIdentifier'
  legacyDeleteResponse:
    type: object
  legacyGetAvailableSectionsRequest:
    type: object
    properties:
      partialIdentifier:
        $ref: '#/definitions/legacyIdentifier'
        title: partial_identifier must contain a partner_id and optionally business_id or market_id
      appIds:
        type: array
        items:
          type: string
      locale:
        type: string
  legacyGetAvailableSectionsResponse:
    type: object
    properties:
      sections:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacySectionSettings'
  legacyGetRequest:
    type: object
    properties:
      identifier:
        $ref: '#/definitions/legacyIdentifier'
  legacyGetResponse:
    type: object
    properties:
      computed:
        $ref: '#/definitions/legacyPreference'
        title: |-
          computed is a full set of preferences, with default values inheriting values from their "parent" LegacyNotificationPreference.
          The inheritance chain from parent to child by what fields are included on the key is as follows:
             partner_id
             partner_id & market_id
             partner_id & user_id
             partner_id & user_id & business_id (market_id optional)
      components:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyPreference'
        description: components are the individual LegacyNotificationPreference entries that are used in the inheritance.
      defaults:
        $ref: '#/definitions/legacyPreference'
        title: defaults represents the default value for each setting and is the equivalent to computed of the nearest parent
      userNotificationsDisabled:
        type: boolean
        description: |-
          user_notifications_disabled is false if the the master notification toggle for the SMB persona is disabled.
          If the identifier does not inlude a user_id this field is unset.
  legacyIdentifier:
    type: object
    properties:
      partnerId:
        type: string
        description: partner_id is always required.
      marketId:
        type: string
        description: market_id is required on create but optional on other operations to entries with a business_id.
      userId:
        type: string
        description: user_id is a universal user id, required if business_id is set.
      businessId:
        type: string
        description: business_id refers to an account_group_id.
    description: Identifier is a reference to a LegacyNotificationPreference.
  legacyListRequest:
    type: object
    properties:
      partialIdentifier:
        $ref: '#/definitions/legacyIdentifier'
        description: partial_identifier can contain just a a partner_id and a user_id to list by account groups, or a partner_id and account_group to list by user.
      cursor:
        type: string
        title: cursor should be supplied from the last response or ""
      pageSize:
        type: string
        format: int64
        description: the number of results to retrieve, pages are not guaranteed to be full length as there may be results removed by access checks.
  legacyListResponse:
    type: object
    properties:
      computed:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyPreference'
        title: |-
          computed is a full set of preferences, with default values inheriting values from their "parent" LegacyNotificationPreference.
          See GetResponse for details on inheritance
      cursor:
        type: string
      hasMore:
        type: boolean
  legacyNotificationActivity:
    type: object
    properties:
      notificationId:
        type: string
      title:
        type: string
      localizedTitle:
        type: string
      tags:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyNotificationSetting'
  legacyNotificationSetting:
    type: object
    properties:
      notificationId:
        type: string
      status:
        $ref: '#/definitions/v1legacyStatus'
      title:
        type: string
      localizedTitle:
        type: string
    description: NotificationSetting is an individual setting. It is intended to be used as a repeated field, to allow key value pairs of IDs to Status values. One acception is a section, which is a special case where NotificationSetting is not repeated.
  legacyPreference:
    type: object
    properties:
      identifier:
        $ref: '#/definitions/legacyIdentifier'
      instantSettings:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyNotificationSetting'
        description: |-
          instant_settings is a list of NS notification IDs (usually of the form 'appId:notifcationName') for which a notification should be sent immediately.
          IDs for which a corresponding entry are not found are considered to be equivalent to STATUS_DEFAULT.
      digestSettings:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyNotificationSetting'
        description: |-
          digest_settings is a list of NS notification IDs (usually of the form 'appId:notifcationName') which should be included in the daily digest.
          IDs for which a corresponding entry are not found are considered to be equivalent to STATUS_DEFAULT.
      executiveReportSettings:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyNotificationSetting'
        description: |-
          executive_report_settings is a list of executive report frequencies that a user may receive an executive report.
          IDs for which a corresponding entry are not found are considered to be equivalent to STATUS_DEFAULT.
      instant:
        $ref: '#/definitions/v1legacyStatus'
        description: Instant refers to if immediate emails should be sent when the event happens.
      digest:
        $ref: '#/definitions/v1legacyStatus'
        description: Digest refers to if emails should be sent when .
      monthlyTaskReport:
        $ref: '#/definitions/v1legacyStatus'
        description: MonthlyTaskReport refers to a specific notification type from concierge. This is maintained to keep compatibility with NS's model.
  legacyProduct:
    type: object
    properties:
      productId:
        type: string
      title:
        type: string
      activities:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyNotificationActivity'
  legacySectionSettings:
    type: object
    properties:
      section:
        $ref: '#/definitions/legacyNotificationSetting'
        title: defined https://github.com/vendasta/NS/blob/854d893026892179744208046db9f7fe06dadea3/src/app/notification_settings/_notification_settings.py#L74-L128
      products:
        type: array
        items:
          type: object
          $ref: '#/definitions/legacyProduct'
        title: defined https://github.com/vendasta/NS/blob/854d893026892179744208046db9f7fe06dadea3/src/app/domain/settings.py#L146-L196
  legacyUpdateRequest:
    type: object
    properties:
      identifier:
        $ref: '#/definitions/legacyIdentifier'
      changes:
        $ref: '#/definitions/legacyPreference'
  legacyUpdateResponse:
    type: object
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v1legacyStatus:
    type: string
    enum:
      - STATUS_UNSET
      - STATUS_DEFAULT
      - STATUS_ENABLED
      - STATUS_DISABLED
    default: STATUS_UNSET
