swagger: "2.0"
info:
  title: sequences/v1/api.proto
  version: version not set
tags:
  - name: Sequences
  - name: Steps
consumes:
  - application/json
produces:
  - application/json
paths:
  /sequences.v1.Sequences/CreateAutomation:
    post:
      operationId: Sequences_CreateAutomation
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateAutomationResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateAutomationRequest'
      tags:
        - Sequences
  /sequences.v1.Sequences/CreateSequence:
    post:
      summary: Creates a sequence
      operationId: Sequences_CreateSequence
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateSequenceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateSequenceRequest'
      tags:
        - Sequences
  /sequences.v1.Sequences/GetSequence:
    post:
      operationId: Sequences_GetSequence
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetSequenceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetSequenceRequest'
      tags:
        - Sequences
  /sequences.v1.Sequences/ListSequences:
    post:
      summary: Lists sequences belonging to a given namespace
      operationId: Sequences_ListSequences
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListSequencesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListSequencesRequest'
      tags:
        - Sequences
  /sequences.v1.Sequences/ListStepTypes:
    post:
      summary: Lists sequence step types
      operationId: Sequences_ListStepTypes
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListStepTypesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListStepTypesRequest'
      tags:
        - Sequences
  /sequences.v1.Steps/CreateSteps:
    post:
      operationId: Steps_CreateSteps
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateStepsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateStepsRequest'
      tags:
        - Steps
  /sequences.v1.Steps/UpdateStep:
    post:
      summary: Update a step
      operationId: Steps_UpdateStep
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateStepResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1UpdateStepRequest'
      tags:
        - Steps
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CreateAutomationRequest:
    type: object
    properties:
      namespace:
        type: string
        title: The namespace of the sequence (e.g., partner id, business id, Yesware account id)
      sequenceId:
        type: string
        title: The ID of the sequence that will be used as a "recipe" to construct the automation
  v1CreateAutomationResponse:
    type: object
    properties:
      automationId:
        type: string
  v1CreateSequenceRequest:
    type: object
    properties:
      type:
        type: string
        title: The type of sequence (e.g., sales, marketing)
      namespace:
        type: string
        title: The namespace of the sequence (e.g., partner id, business id, Yesware account id)
      displayName:
        type: string
        title: The display name of the sequence
    title: Sequence creation
  v1CreateSequenceResponse:
    type: object
    properties:
      sequenceId:
        type: string
  v1CreateStepsRequest:
    type: object
    properties:
      namespace:
        type: string
        title: The namespace of the parent sequence
      sequenceId:
        type: string
        title: The ID of the parent sequence
      orderedStepList:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1StepInput'
        title: The list of steps to create for the given sequence
  v1CreateStepsResponse:
    type: object
    properties:
      orderedStepIdList:
        type: array
        items:
          type: string
        title: The list of step IDs created
  v1GetSequenceRequest:
    type: object
    properties:
      sequenceId:
        type: string
  v1GetSequenceResponse:
    type: object
    properties:
      sequence:
        $ref: '#/definitions/v1SequenceData'
      steps:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1StepData'
  v1ListSequencesRequest:
    type: object
    properties:
      namespace:
        type: string
  v1ListSequencesResponse:
    type: object
    properties:
      sequenceList:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1SequenceData'
        description: Paging information coming soon.
        title: The actual list of sequences
    title: Response from getting a list of sequences
  v1ListStepTypesRequest:
    type: object
    properties:
      sequenceType:
        type: string
  v1ListStepTypesResponse:
    type: object
    properties:
      stepTypeList:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1StepTypeData'
        title: The list of step types available for the given sequence type
  v1SequenceData:
    type: object
    properties:
      namespace:
        type: string
      type:
        type: string
      sequenceId:
        type: string
      name:
        type: string
      orderedStepIds:
        type: array
        items:
          type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    title: Sequence listing
  v1StepData:
    type: object
    properties:
      stepId:
        type: string
      name:
        type: string
  v1StepInput:
    type: object
    properties:
      displayName:
        type: string
        title: The display name for the step
      delaySeconds:
        type: string
        format: int64
        title: The delay in seconds before the step is executed
      taskDefinitionId:
        type: string
        title: The Task ID from the Automation Task, signifies the step type
      taskInputData:
        type: string
        title: Input data is freeform json of the data passed into the task
    title: Input needed to create a single step
  v1StepTypeData:
    type: object
    properties:
      nameKey:
        type: string
      taskDefinitionId:
        type: string
    title: Sequence step types
  v1UpdateStepRequest:
    type: object
    properties:
      stepId:
        type: string
      step:
        $ref: '#/definitions/v1StepData'
      fieldMask:
        $ref: '#/definitions/vendastatypesFieldMask'
  v1UpdateStepResponse:
    type: object
    properties:
      stepId:
        type: string
      name:
        type: string
  vendastatypesFieldMask:
    type: object
    properties:
      paths:
        type: array
        items:
          type: string
        description: The set of field mask paths.
    description: |-
      paths: "f.a"
          paths: "f.b.d"

      Here `f` represents a field in some root message, `a` and `b`
      fields in the message found in `f`, and `d` a field found in the
      message in `f.b`.

      Field masks are used to specify a subset of fields that should be
      returned by a get operation or modified by an update operation.
      Field masks also have a custom JSON encoding (see below).

      # Field Masks in Projections

      When used in the context of a projection, a response message or
      sub-message is filtered by the API to only contain those fields as
      specified in the mask. For example, if the mask in the previous
      example is applied to a response message as follows:

          f {
            a : 22
            b {
              d : 1
              x : 2
            }
            y : 13
          }
          z: 8

      The result will not contain specific values for fields x,y and z
      (their value will be set to the default, and omitted in proto text
      output):


          f {
            a : 22
            b {
              d : 1
            }
          }

      A repeated field is not allowed except at the last position of a
      paths string.

      If a FieldMask object is not present in a get operation, the
      operation applies to all fields (as if a FieldMask of all fields
      had been specified).

      Note that a field mask does not necessarily apply to the
      top-level response message. In case of a REST get operation, the
      field mask applies directly to the response, but in case of a REST
      list operation, the mask instead applies to each individual message
      in the returned resource list. In case of a REST custom method,
      other definitions may be used. Where the mask applies will be
      clearly documented together with its declaration in the API.  In
      any case, the effect on the returned resource/resources is required
      behavior for APIs.

      # Field Masks in Update Operations

      A field mask in update operations specifies which fields of the
      targeted resource are going to be updated. The API is required
      to only change the values of the fields as specified in the mask
      and leave the others untouched. If a resource is passed in to
      describe the updated values, the API ignores the values of all
      fields not covered by the mask.

      If a repeated field is specified for an update operation, the existing
      repeated values in the target resource will be overwritten by the new values.
      Note that a repeated field is only allowed in the last position of a `paths`
      string.

      If a sub-message is specified in the last position of the field mask for an
      update operation, then the existing sub-message in the target resource is
      overwritten. Given the target message:

          f {
            b {
              d : 1
              x : 2
            }
            c : 1
          }

      And an update message:

          f {
            b {
              d : 10
            }
          }

      then if the field mask is:

       paths: "f.b"

      then the result will be:

          f {
            b {
              d : 10
            }
            c : 1
          }

      However, if the update mask was:

       paths: "f.b.d"

      then the result would be:

          f {
            b {
              d : 10
              x : 2
            }
            c : 1
          }

      In order to reset a field's value to the default, the field must
      be in the mask and set to the default value in the provided resource.
      Hence, in order to reset all fields of a resource, provide a default
      instance of the resource and set all fields in the mask, or do
      not provide a mask as described below.

      If a field mask is not present on update, the operation applies to
      all fields (as if a field mask of all fields has been specified).
      Note that in the presence of schema evolution, this may mean that
      fields the client does not know and has therefore not filled into
      the request will be reset to their default. If this is unwanted
      behavior, a specific service may require a client to always specify
      a field mask, producing an error if not.

      As with get operations, the location of the resource which
      describes the updated values in the request message depends on the
      operation kind. In any case, the effect of the field mask is
      required to be honored by the API.

      ## Considerations for HTTP REST

      The HTTP kind of an update operation which uses a field mask must
      be set to PATCH instead of PUT in order to satisfy HTTP semantics
      (PUT must only be used for full updates).

      # JSON Encoding of Field Masks

      In JSON, a field mask is encoded as a single string where paths are
      separated by a comma. Fields name in each path are converted
      to/from lower-camel naming conventions.

      As an example, consider the following message declarations:

          message Profile {
            User user = 1;
            Photo photo = 2;
          }
          message User {
            string display_name = 1;
            string address = 2;
          }

      In proto a field mask for `Profile` may look as such:

          mask {
            paths: "user.display_name"
            paths: "photo"
          }

      In JSON, the same mask is represented as below:

          {
            mask: "user.displayName,photo"
          }

      # Field Masks and Oneof Fields

      Field masks treat fields in oneofs just as regular fields. Consider the
      following message:

          message SampleMessage {
            oneof test_oneof {
              string name = 4;
              SubMessage sub_message = 9;
            }
          }

      The field mask can be:

          mask {
            paths: "name"
          }

      Or:

          mask {
            paths: "sub_message"
          }

      Note that oneof type names ("test_oneof" in this case) cannot be used in
      paths.
    title: '`FieldMask` represents a set of symbolic field paths, for example:'
