swagger: "2.0"
info:
  title: url_shortener/v1/api.proto
  version: version not set
tags:
  - name: UrlShortener
consumes:
  - application/json
produces:
  - application/json
paths:
  /url_shortener.v1.UrlShortener/CreateLink:
    post:
      summary: CreateLink returns the short_code for a link
      operationId: UrlShortener_CreateLink
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateLinkResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateLinkRequest'
      tags:
        - UrlShortener
  /url_shortener.v1.UrlShortener/GetLink:
    post:
      summary: GetLink fetches the link by short_code
      operationId: UrlShortener_GetLink
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetLinkResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetLinkRequest'
      tags:
        - UrlShortener
  /url_shortener.v1.UrlShortener/GetMultiLinkMetrics:
    post:
      summary: GetMultiLinkMetrics gets the metrics for links
      operationId: UrlShortener_GetMultiLinkMetrics
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetMultiLinkMetricsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetMultiLinkMetricsRequest'
      tags:
        - UrlShortener
  /url_shortener.v1.UrlShortener/ListAllLinkMetrics:
    post:
      summary: ListLinkMetrics lists the metrics for link with sorted_field, filter_term and paging options
      operationId: UrlShortener_ListAllLinkMetrics
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListAllLinkMetricsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListAllLinkMetricsRequest'
      tags:
        - UrlShortener
  /url_shortener.v1.UrlShortener/ListLinks:
    post:
      summary: ListLinks fetches all linkUrl and shortCode matches
      operationId: UrlShortener_ListLinks
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListLinksResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListLinksRequest'
      tags:
        - UrlShortener
  /url_shortener.v1.UrlShortener/SetLinkHideStatuses:
    post:
      summary: SetLinkHideStatuses sets the hidden bool on the Link entity
      operationId: UrlShortener_SetLinkHideStatuses
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetLinkHideStatusesRequest'
      tags:
        - UrlShortener
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CreateLinkRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The unique business id (optional for some owners)
      linkUrl:
        type: string
        title: The url that is shortened
      owner:
        $ref: '#/definitions/v1Owner'
        title: Owner of the link
      description:
        type: string
        title: Description of the link
      hidden:
        type: boolean
        title: Hide whether the link will show up in list results
      sensitiveUrl:
        type: boolean
        title: |-
          Setting sensitive_url to true will increase the length of the short_code as well as hash the short_code and the link_url
          Should be used for sensitive URLs like password reset
    title: Request for create a link with a business id
  v1CreateLinkResponse:
    type: object
    properties:
      shortCode:
        type: string
        title: The unique code for a link
      domain:
        type: string
        title: The domain for a link
    title: Response returns a short_code
  v1GetLinkRequest:
    type: object
    properties:
      shortCode:
        type: string
        title: The unique code for a link
    title: Request for getting the link with business id and short code
  v1GetLinkResponse:
    type: object
    properties:
      link:
        $ref: '#/definitions/v1Link'
        title: The link object
    title: Response returns a link
  v1GetMultiLinkMetricsRequest:
    type: object
    properties:
      shortCode:
        type: array
        items:
          type: string
        title: The unique code for a link
    title: Request for getting metrics for links
  v1GetMultiLinkMetricsResponse:
    type: object
    properties:
      linkMetrics:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1LinkMetrics'
        title: A list of metrics for links
    title: Reponse returns a list of metrics for links and paging meta data
  v1Link:
    type: object
    properties:
      shortCode:
        type: string
        title: The "code" for the link
      longUrl:
        type: string
        title: The url that is shortened
      businessId:
        type: string
        title: The business id associated with this link (optional for some owners)
      created:
        type: string
        format: date-time
        title: When the shortened link was created
      owner:
        $ref: '#/definitions/v1Owner'
        title: The owner of the link
      description:
        type: string
        title: The description of the link
      hidden:
        type: string
        format: date-time
        title: If not empty the link will show up in list results
    title: Information about a shortened link
  v1LinkMetrics:
    type: object
    properties:
      totalHits:
        type: string
        format: int64
        title: number of hits for a link
      referers:
        type: object
        additionalProperties:
          type: string
          format: int64
        title: number of hits originating from each referer
      shortCode:
        type: string
        title: The unique code for a link
      longUrl:
        type: string
        title: The url that is shortened
      created:
        type: string
        format: date-time
        title: When the shortened link was created
      description:
        type: string
        title: Description of the link
    title: Metrics measuring a link's performance
  v1ListAllLinkMetricsRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The unique business id
      sortField:
        $ref: '#/definitions/v1SortField'
        title: The field need to be sorted
      filterTerm:
        type: string
        title: The term need to be filtered
      sortDirection:
        $ref: '#/definitions/v1SortDirection'
        title: Direction for sorting
      owner:
        $ref: '#/definitions/v1Owner'
        title: Owner of link to list by
    title: Request for listing metrics for a business_id with filtered link and sorted field
  v1ListAllLinkMetricsResponse:
    type: object
    properties:
      linkMetrics:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1LinkMetrics'
        title: A list of metrics for links
    title: Reponse returns a list of metrics for links and paging meta data
  v1ListLinksRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The unique business id
      options:
        $ref: '#/definitions/v1PagedRequestOptions'
        title: Options for how to page the response for this request
      owner:
        $ref: '#/definitions/v1Owner'
        title: Owner of link to list by
    title: Request for getting all matches of longUrl and shortCode associate with business id
  v1ListLinksResponse:
    type: object
    properties:
      link:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Link'
        title: a match of longUrl and shortCode
      pagingMetadata:
        $ref: '#/definitions/v1PagedResponseMetadata'
        title: Metadata about the paged response
    title: Reponse for getting all matches of longUrl and shortCode associate with business id
  v1Owner:
    type: string
    enum:
      - OWNER_NOT_SPECIFIED
      - OWNER_SOCIAL_MARKETING
      - OWNER_CUSTOMER_VOICE
      - OWNER_CORE_SERVICES
      - OWNER_EMAIL_VERIFICATION
      - OWNER_SMB_REFERRAL
      - OWNER_UNTRACKED
      - OWNER_INBOX_BUSINESS
      - OWNER_REPUTATION_MANAGEMENT
    default: OWNER_NOT_SPECIFIED
    description: |-
      - OWNER_UNTRACKED: The UNTRACKED owner is for simple "CreateLink" calls that aren't associated to a business.
      This owner does not support listing links or list metrics, and does not require links to be associated to a
      business ID.
      This is useful for one-off links like password reset links or email verification links,
      but shouldn't be used for anything that requires click tracking like links in marketing emails, etc.
    title: Different link owners
  v1PagedRequestOptions:
    type: object
    properties:
      cursor:
        type: string
        title: cursor can be passed to retrieve the next page of results keyed by the cursor
      pageSize:
        type: string
        format: int64
        title: page_size specifies the number of items to return in the next page
    title: Options for how to page the response for a List request
  v1PagedResponseMetadata:
    type: object
    properties:
      nextCursor:
        type: string
        title: A cursor that can be provided to retrieve the next page of results
      hasMore:
        type: boolean
        title: Whether or not more results exist
    title: Metadata related to the paged response from a List request
  v1SetLinkHideStatusesRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The unique business id
      shortCodes:
        type: array
        items:
          type: string
        title: A list of shortened links
      hidden:
        type: boolean
        title: Determines whether the links should be hidden or not
    title: Request for setting the hidden field on a list of links
  v1SortDirection:
    type: string
    enum:
      - SORT_DIRECTION_DESCENDING
      - SORT_DIRECTION_ASCENDING
    default: SORT_DIRECTION_DESCENDING
    title: The directions that a result set can be sorted in
  v1SortField:
    type: string
    enum:
      - SORT_FIELD_CREATED
      - SORT_FIELD_LONGURL
      - SORT_FIELD_FACEBOOK
      - SORT_FIELD_TWITTER
      - SORT_FIELD_LINKEDIN
      - SORT_FIELD_GOOGLE
      - SORT_FIELD_OTHER
      - SORT_FIELD_TOTAL
    default: SORT_FIELD_CREATED
    title: The terms that a filter can set
