swagger: "2.0"
info:
  title: quickbooks/v1/api.proto
  version: version not set
tags:
  - name: QuickBooks
consumes:
  - application/json
produces:
  - application/json
paths:
  /quickbooks.v1.QuickBooks/GetAccountsPayableAgingSummary:
    post:
      summary: Gets the accounts payable aging summary
      operationId: QuickBooks_GetAccountsPayableAgingSummary
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAgingSummaryResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAgingSummaryRequest'
      tags:
        - QuickBooks
  /quickbooks.v1.QuickBooks/GetAccountsReceivableAgingSummary:
    post:
      summary: Gets the account receivable aging summary
      operationId: QuickBooks_GetAccountsReceivableAgingSummary
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAgingSummaryResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAgingSummaryRequest'
      tags:
        - QuickBooks
  /quickbooks.v1.QuickBooks/GetAuthorizationCodeRedirectURL:
    post:
      summary: Get the URL for authorization redirects, this url will grant our app access to the users QuickBooks company
      operationId: QuickBooks_GetAuthorizationCodeRedirectURL
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAuthorizationCodeRedirectURLResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAuthorizationCodeRedirectURLRequest'
      tags:
        - QuickBooks
  /quickbooks.v1.QuickBooks/GetConnectedCompany:
    post:
      summary: Gets the information of the Quickbooks Company that is connected to the given Business
      operationId: QuickBooks_GetConnectedCompany
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetConnectedCompanyResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetConnectedCompanyRequest'
      tags:
        - QuickBooks
  /quickbooks.v1.QuickBooks/GetProfitAndLoss:
    post:
      summary: Gets the profit and loss report for products and services
      operationId: QuickBooks_GetProfitAndLoss
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetProfitAndLossResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetProfitAndLossRequest'
      tags:
        - QuickBooks
  /quickbooks.v1.QuickBooks/RevokeAccessToken:
    post:
      summary: Revoke access token to Quickbooks
      operationId: QuickBooks_RevokeAccessToken
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1RevokeAccessTokenRequest'
      tags:
        - QuickBooks
definitions:
  GetProfitAndLossResponseSection:
    type: object
    properties:
      rows:
        type: array
        items:
          type: object
          $ref: '#/definitions/GetProfitAndLossResponseSectionRow'
        title: A list of rows
      total:
        type: string
        title: The total value for all rows
    title: Section of data in the profit and loss report
  GetProfitAndLossResponseSectionRow:
    type: object
    properties:
      column:
        $ref: '#/definitions/RowColumnData'
    title: A row of data for the section
  RowColumnData:
    type: object
    properties:
      title:
        type: string
        title: product/service name
      value:
        type: string
        title: income/expense values
    title: The values in the row for the section
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Company:
    type: object
    properties:
      name:
        type: string
    title: Company information from QuickBooks
  v1ConnectionInfo:
    type: object
    properties:
      name:
        type: string
        title: The name of the connection
      logoUrl:
        type: string
        title: The url for the logo of the connection
      serviceProviderId:
        type: string
        title: The service provider ID used by Atlas
      entryUrl:
        type: string
        title: The url to enter the connection
    title: Connection information for accessing Quickbooks
  v1GetAgingSummaryRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business to get the aging summary for
      userId:
        type: string
        title: The user id required for getting auth token
    title: Request to get the aging summary
  v1GetAgingSummaryResponse:
    type: object
    properties:
      currency:
        type: string
        title: Currency the report is in
      row:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1GetAgingSummaryResponseRow'
        title: A list of rows
    title: Returns the data from the aging summary
  v1GetAgingSummaryResponseRow:
    type: object
    properties:
      columnValue:
        type: array
        items:
          type: string
        title: |-
          The values in the row for the customer
          e.g., customer name, owing values for aging periods, owing total
    title: A row of data for a QB customer
  v1GetAuthorizationCodeRedirectURLRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business that this connection is going to be made for
      userId:
        type: string
        title: The id the user who has authed the quickbooks connection
    title: Request for the authorization redirect url
  v1GetAuthorizationCodeRedirectURLResponse:
    type: object
    properties:
      url:
        type: string
        title: The URL to redirect the user to to acquire their QuickBooks authorization
    title: Returns the redirect URL
  v1GetConnectedCompanyRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business to search for the connected Company with
      userId:
        type: string
        title: The id the user who has authed the quickbooks connection
    title: Request the connected Company information
  v1GetConnectedCompanyResponse:
    type: object
    properties:
      company:
        $ref: '#/definitions/v1Company'
      connectionInfo:
        $ref: '#/definitions/v1ConnectionInfo'
        title: The connection info for this company
    title: Returns the QuickBooks Company information
  v1GetProfitAndLossRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business to get the profit and loss report for
      userId:
        type: string
        title: The user id required for getting auth token
      startDate:
        type: string
        format: date-time
        title: The report's start period
      endDate:
        type: string
        format: date-time
        title: The report's end period
    title: Request to get the profit and loss report
  v1GetProfitAndLossResponse:
    type: object
    properties:
      currency:
        type: string
        title: Currency the report is in
      income:
        $ref: '#/definitions/GetProfitAndLossResponseSection'
        title: Section of data for the income
      expenses:
        $ref: '#/definitions/GetProfitAndLossResponseSection'
        title: Section of data for the expenses
    title: Returns the data from the profit and loss report
  v1RevokeAccessTokenRequest:
    type: object
    properties:
      businessId:
        type: string
        title: The business that we will revoke the access token for
      userId:
        type: string
        title: The id the user who has authed the quickbooks connection
    title: Request to revoke access token
