swagger: "2.0"
info:
  title: order_fulfillment/v1/fulfillment_form_submission.proto
  version: version not set
tags:
  - name: FulfillmentFormSubmissionService
consumes:
  - application/json
produces:
  - application/json
paths:
  /orderfulfillment.v1.FulfillmentFormSubmissionService/GetLatestFulfillmentFormSubmission:
    post:
      summary: Retrieve a fulfillment order
      operationId: FulfillmentFormSubmissionService_GetLatestFulfillmentFormSubmission
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetLatestFulfillmentFormSubmissionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetLatestFulfillmentFormSubmissionRequest'
      tags:
        - FulfillmentFormSubmissionService
  /orderfulfillment.v1.FulfillmentFormSubmissionService/UpsertFulfillmentFormSubmission:
    post:
      summary: Update a fulfillment order
      operationId: FulfillmentFormSubmissionService_UpsertFulfillmentFormSubmission
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpsertFulfillmentFormSubmissionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1UpsertFulfillmentFormSubmissionRequest'
      tags:
        - FulfillmentFormSubmissionService
definitions:
  FulfillmentFormFieldOption:
    type: object
    properties:
      label:
        type: string
      value:
        type: string
    title: Stores the valid set of options with display text and internal value. Both fields will always be populated
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CustomFields:
    type: object
    properties:
      fields:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Field'
  v1Field:
    type: object
    properties:
      fieldId:
        type: string
        title: Unique identifier of a custom or common field
      answer:
        type: string
        title: Response related to the question of the field_id
      fieldType:
        $ref: '#/definitions/v1FieldType'
        title: The type of field
      label:
        type: string
        title: The question for the custom or common field
      description:
        type: string
        title: The description of the field
      prefix:
        type: string
        title: For textbox fields, this string will be displayed in front of the textbox
      suffix:
        type: string
        title: For textbox fields, this string will be displayed behind the textbox
      regexValidator:
        type: string
        title: A regex string used to validate a fields answer
      regexErrorMessage:
        type: string
        title: The error message displayed if the regex_validator does not match the answer
  v1FieldType:
    type: string
    enum:
      - FIELD_TYPE_NOT_SPECIFIED
      - FIELD_TYPE_TEXT
      - FIELD_TYPE_TEXT_AREA
      - FIELD_TYPE_DROPDOWN
      - FIELD_TYPE_CHECKBOX
      - FIELD_TYPE_FILE
      - FIELD_TYPE_VBCUSER
    default: FIELD_TYPE_NOT_SPECIFIED
  v1FormAnswers:
    type: object
    properties:
      formId:
        type: string
      customFields:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1CustomFields'
  v1FulfillmentFormConfig:
    type: object
    properties:
      orderForm:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1FulfillmentFormField'
        title: 'Fulfillment form: fields in the fulfillment form'
      activationMessage:
        type: string
        title: 'Fulfillment form: message shown to users upon activating the app'
      separateOrderForms:
        type: boolean
        title: 'Fulfillment form: should a multi-activatable app/addon use a separate order form for each activation'
      usesPostBillingOrderForm:
        type: boolean
        title: 'Fulfillment form: whether or not the order form is to be used post-billing'
      footerText:
        type: string
        title: 'Fulfillment form: footer text'
    title: Setup for a fulfillment form
  v1FulfillmentFormField:
    type: object
    properties:
      label:
        type: string
      id:
        type: string
      type:
        type: string
      description:
        type: string
      required:
        type: boolean
      prefix:
        type: string
        title: For textbox fields, this string will be displayed in front of the textbox
      suffix:
        type: string
        title: For textbox fields, this string will be displayed behind the textbox
      regexValidator:
        type: string
        title: A regex string used to validate a fields answer
      regexErrorMessage:
        type: string
        title: The error message displayed if the regex_validator does not match the answer
      useWebhookValidator:
        type: boolean
        title: Indicates if this field will call out to the order_form_validator_webhook_url under Integration
      allowMultiples:
        type: boolean
        description: |-
          The following 3 options are for dropdowns that allow you to choose multiple options
          Whether or not to allow multiple choices.
      allowDuplicates:
        type: boolean
        description: If you should be able to choose the same option twice.
      maxChoices:
        type: string
        format: int64
        title: The maximum number of choices you can make
      forOfficeUseOnly:
        type: boolean
        title: if this is true the field will not be shown to end users
      optionsWithLabels:
        type: array
        items:
          type: object
          $ref: '#/definitions/FulfillmentFormFieldOption'
      officeEditableOnly:
        type: boolean
        title: if this is true the field will not be editable by end users
    title: |-
      Mostly copied from Order Form in marketplace-apps
      Field asking user for information when they try to activate the app
  v1FulfillmentFormSubmission:
    type: object
    properties:
      fulfillmentOrderId:
        type: string
        description: The FulfillmentOrder this is attached to.
      salesOrderId:
        type: string
        description: The sales order the submission is for.
      appId:
        type: string
        description: The app in the sales order this form is tied to.
      version:
        type: string
        description: Timestamp of when this was submitted, in UTC.
      userId:
        type: string
        description: User ID who submitted this form.
      quantity:
        type: string
        format: int64
        description: Number of instances of the app in the sales order. Deprecated.
      formAnswers:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1FormAnswers'
        description: Custom fields answers for this form.
      formConfig:
        $ref: '#/definitions/v1FulfillmentFormConfig'
        description: The configuration for the form being answered.
      created:
        type: string
        format: date-time
        title: Time the fulfillment order was created
      updated:
        type: string
        format: date-time
        title: Time the fulfillment order was updated
      deleted:
        type: string
        format: date-time
        title: Time the fulfillment order was deleted
  v1GetLatestFulfillmentFormSubmissionRequest:
    type: object
    properties:
      salesOrderId:
        type: string
      appId:
        type: string
      businessId:
        type: string
  v1GetLatestFulfillmentFormSubmissionResponse:
    type: object
    properties:
      fulfillmentFormSubmission:
        $ref: '#/definitions/v1FulfillmentFormSubmission'
  v1UpsertFulfillmentFormSubmissionRequest:
    type: object
    properties:
      salesOrderId:
        type: string
      appId:
        type: string
      businessId:
        type: string
      formAnswers:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1FormAnswers'
      lastViewedTimestamp:
        type: string
      quantity:
        type: string
        format: int64
  v1UpsertFulfillmentFormSubmissionResponse:
    type: object
    properties:
      version:
        type: string
