swagger: "2.0"
info:
  title: address/v1/api.proto
  version: version not set
tags:
  - name: Address
consumes:
  - application/json
produces:
  - application/json
paths:
  /address.v1.Address/DeleteLocalizedZone:
    post:
      summary: Delete zone entry for a country, zone, and locale
      operationId: Address_DeleteLocalizedZone
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeleteLocalizedZoneRequest'
      tags:
        - Address
  /address.v1.Address/GetCountryConfiguration:
    post:
      summary: GetCountryConfiguration request
      operationId: Address_GetCountryConfiguration
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetCountryConfigurationResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetCountryConfigurationRequest'
      tags:
        - Address
  /address.v1.Address/ListAllCountryOptions:
    post:
      summary: List all countries for a locale
      operationId: Address_ListAllCountryOptions
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListAllCountryOptionsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListAllCountryOptionsRequest'
      tags:
        - Address
  /address.v1.Address/ReplaceCountryFormatting:
    post:
      summary: Replace country formatting for a country
      operationId: Address_ReplaceCountryFormatting
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ReplaceCountryFormattingRequest'
      tags:
        - Address
  /address.v1.Address/ReplaceLocalizedCountry:
    post:
      summary: Replace country information for a country and locale
      operationId: Address_ReplaceLocalizedCountry
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ReplaceLocalizedCountryRequest'
      tags:
        - Address
  /address.v1.Address/ReplaceLocalizedZone:
    post:
      summary: Replace zone information for a country, zone, and locale
      operationId: Address_ReplaceLocalizedZone
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ReplaceLocalizedZoneRequest'
      tags:
        - Address
definitions:
  CountryConfigurationFormatting:
    type: object
    properties:
      show:
        type: string
        title: The templated format string for showing an address for this country
      edit:
        type: string
        title: The templated format string for editing an address for this country
      required:
        type: array
        items:
          type: string
        title: The required address form fields for editing an address for this country
  CountryConfigurationLabels:
    type: object
    properties:
      address1:
        type: string
        title: The label for the first address line field
      address2:
        type: string
        title: The label for the second address line field
      city:
        type: string
        title: The label for the city field
      company:
        type: string
        title: The label for the company name field
      country:
        type: string
        title: The label for the country field
      firstName:
        type: string
        title: The label for the first name field
      lastName:
        type: string
        title: The label for the last name field
      phone:
        type: string
        title: The label for the phone number field
      postalCode:
        type: string
        title: The label for the postal code field
      zone:
        type: string
        title: The label for the zone field
  CountryConfigurationZone:
    type: object
    properties:
      code:
        type: string
        title: The code of this zone
      name:
        type: string
        title: The localized name of this zone
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CountryConfiguration:
    type: object
    properties:
      code:
        type: string
        title: The two-letter country code for this country
      continent:
        type: string
        title: The localized name of the continent of this country
      name:
        type: string
        title: The localized name of this country
      phoneNumberPrefix:
        type: string
        format: int64
        title: The phone number prefix this country uses
      formatting:
        $ref: '#/definitions/CountryConfigurationFormatting'
        title: The formatting for displaying and editing an address for this country
      labels:
        $ref: '#/definitions/CountryConfigurationLabels'
        title: The localized labels for address form fields
      zones:
        type: array
        items:
          type: object
          $ref: '#/definitions/CountryConfigurationZone'
        title: A localized zone (province, state, etc.) for this country
      locale:
        type: string
        title: The locale used for localizing this information
    title: Information for displaying and editing an address in a given localization
  v1CountryOption:
    type: object
    properties:
      code:
        type: string
        title: The two-letter country code for this country
      name:
        type: string
        title: The localized name of this country
    title: Shorthand information for displaying countries in form options
  v1DeleteLocalizedZoneRequest:
    type: object
    properties:
      locale:
        type: string
        title: The locale for this country localization
      countryCode:
        type: string
        title: The two-letter country code of the country
      zoneCode:
        type: string
        title: The zone code of this zone
    title: Delete zone information for a particular locale
  v1GetCountryConfigurationRequest:
    type: object
    properties:
      countryCode:
        type: string
        title: The two-letter country code of the country to get details for
      locale:
        type: string
        description: Localize information into this locale, if provided. Use default locale otherwise.
    title: Retrieve formatting, zones, and country information for a give country code and locale
  v1GetCountryConfigurationResponse:
    type: object
    properties:
      country:
        $ref: '#/definitions/v1CountryConfiguration'
        title: The country configuration for a given country code and locale
    title: GetCountryConfigurationResponse returns localized address information for a given country and locale
  v1ListAllCountryOptionsRequest:
    type: object
    properties:
      locale:
        type: string
        title: The locale to fetch
    title: List country options by locale
  v1ListAllCountryOptionsResponse:
    type: object
    properties:
      countryOptions:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1CountryOption'
        title: The country options
    title: Returns a list of country options
  v1ReplaceCountryFormattingRequest:
    type: object
    properties:
      countryCode:
        type: string
        title: The two-letter country code of the country formatting to replace
      showTemplate:
        type: string
        title: The templated format string for showing an address for this country
      editTemplate:
        type: string
        title: The templated format string for editing an address for this country
      requiredTemplate:
        type: string
        title: The string representing the required fields when editing an address for this country
    title: Store a representation for a country's templated formatting
  v1ReplaceLocalizedCountryRequest:
    type: object
    properties:
      locale:
        type: string
        title: The locale for this country localization
      countryCode:
        type: string
        title: The two-letter country code of the country
      name:
        type: string
        title: The localized name of this country
      continent:
        type: string
        title: The localized name of the continent of this country
      phoneNumberPrefix:
        type: string
        format: int64
        title: The phone number prefix this country uses
      address1Label:
        type: string
        title: The label for the first address line field
      address2Label:
        type: string
        title: The label for the second address line field
      cityLabel:
        type: string
        title: The label for the city field
      countryLabel:
        type: string
        title: The label for the country field
      companyLabel:
        type: string
        title: The label for the company name field
      firstNameLabel:
        type: string
        title: The label for the first name field
      lastNameLabel:
        type: string
        title: The label for the last name field
      phoneNumberLabel:
        type: string
        title: The label for the phone number field
      postalCodeLabel:
        type: string
        title: The label for the postal code field
      zoneLabel:
        type: string
        title: The label for the zone field
    title: Store country information in a particular locale
  v1ReplaceLocalizedZoneRequest:
    type: object
    properties:
      locale:
        type: string
        title: The locale for this country localization
      countryCode:
        type: string
        title: The two-letter country code of the country
      zoneCode:
        type: string
        title: The zone code of this zone
      name:
        type: string
        title: The localized name of this zone
    title: Store zone information in a particular locale
