swagger: "2.0"
info:
  title: google_search_console/v1/api.proto
  version: version not set
tags:
  - name: Sites
  - name: Records
consumes:
  - application/json
produces:
  - application/json
paths:
  /googlesearchconsole.v1.Records/CollectRecords:
    post:
      summary: CollectRecords launches the collection of GSC records from a period of time
      operationId: Records_CollectRecords
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CollectRecordsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CollectRecordsRequest'
      tags:
        - Records
  /googlesearchconsole.v1.Records/GetKeywords:
    post:
      summary: GetKeywords gets a list of keywords to be tracked by Google search console
      operationId: Records_GetKeywords
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetKeywordsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetKeywordsRequest'
      tags:
        - Records
  /googlesearchconsole.v1.Records/SetInitialKeywords:
    post:
      summary: SetInitialKeywords launches the collection and storage of top 10 queries
      operationId: Records_SetInitialKeywords
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SetInitialKeywordsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetInitialKeywordsRequest'
      tags:
        - Records
  /googlesearchconsole.v1.Records/SetKeywords:
    post:
      summary: SetKeywords sets a list of keywords to be tracked by Google search console
      operationId: Records_SetKeywords
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SetKeywordsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetKeywordsRequest'
      tags:
        - Records
  /googlesearchconsole.v1.Sites/DeleteSite:
    post:
      summary: DeleteSite deletes a site
      operationId: Sites_DeleteSite
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DeleteSiteResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1DeleteSiteRequest'
      tags:
        - Sites
  /googlesearchconsole.v1.Sites/GetAvailableSites:
    post:
      summary: GetAvailableSites gets all available sites from Google for user to connect
      operationId: Sites_GetAvailableSites
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetAvailableGSCSitesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetAvailableGSCSitesRequest'
      tags:
        - Sites
  /googlesearchconsole.v1.Sites/GetSite:
    post:
      summary: GetSite returns the currently set GSC site for a business
      operationId: Sites_GetSite
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetSiteResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetSiteRequest'
      tags:
        - Sites
  /googlesearchconsole.v1.Sites/LookupSites:
    post:
      summary: LookupSites lookup all the connected sites for a given business
      operationId: Sites_LookupSites
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1LookupSitesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1LookupSitesRequest'
      tags:
        - Sites
  /googlesearchconsole.v1.Sites/SetSite:
    post:
      summary: SetSite sets a business's GSC site for querying
      operationId: Sites_SetSite
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SetSiteResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetSiteRequest'
      tags:
        - Sites
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CollectRecordsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The Partner ID of the account to collect records
      businessId:
        type: string
        title: The Business ID of the account to collect records
      startDate:
        type: string
        format: date-time
        title: The date to start collecting records (inclusive)
      endDate:
        type: string
        format: date-time
        title: the date to end collecting records (inclusive)
  v1CollectRecordsResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The success/fail response
  v1ConnectedSite:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the site is associated with
      businessId:
        type: string
        title: The business ID the site is associated with (aka the account group ID)
      gscSiteUrl:
        type: string
        title: The URL of the site associated with the GSC account
      gscUserId:
        type: string
        title: The user id on the account
      created:
        type: string
        format: date-time
        title: The time the site was first created
      updated:
        type: string
        format: date-time
        title: The last time a site was updated
      isBroken:
        type: boolean
        title: A flag to show whether or not the site is working properly
      deleted:
        type: boolean
        title: if the site is deleted
  v1DeleteSiteRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the site is associated with
      businessId:
        type: string
        title: The business ID the site is associated with (aka the account group ID)
    title: The request sent to flag a site as deleted
  v1DeleteSiteResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The success/fail response when deleting a site
  v1GetAvailableGSCSitesRequest:
    type: object
    properties:
      googleUserId:
        type: string
        title: the User's Google ID
    title: |-
      Request that will query Google for the sites available to the GSC account
      associated with the user's google ID
      This will only be called after a user has granted authorization to connect
      Their GSC account
  v1GetAvailableGSCSitesResponse:
    type: object
    properties:
      sites:
        type: array
        items:
          type: string
        title: Site object to which this user has access
    title: List of sites available to the connected Google Search Console account
  v1GetKeywordsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The partner ID of the business setting the keywords
      businessId:
        type: string
        title: The account group ID of the business setting the keywords
    title: GetKeywordsRequest
  v1GetKeywordsResponse:
    type: object
    properties:
      keywords:
        type: array
        items:
          type: string
        title: The list of keywords to be tracked
    title: GetKeywordsResponse returns list of keywords to be tracked using google search console
  v1GetSiteRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the site is associated with
      businessId:
        type: string
        title: The business ID the site is associated with (aka the account group ID)
    title: Get the current site connected an an account
  v1GetSiteResponse:
    type: object
    properties:
      site:
        type: string
        title: The site struct returned
  v1LookupSitesRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The Partner ID of the business to look up sites
      businessId:
        type: string
        title: The Business ID of the business to look up sites
      cursor:
        type: string
        description: Cursor allows paging of results, the next_cursor returned by the last response is expected.
    title: LookupSitesRequest is the request of getting all connected sites for a given business
  v1LookupSitesResponse:
    type: object
    properties:
      sites:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ConnectedSite'
        title: List of sites that's connected with the business
      nextCursor:
        type: string
        description: A string indicating the starting position of the next set of results. The client should pass this in the next request.
      hasMore:
        type: boolean
        description: A bool indicating if there are more results to be paged through.
    title: LookupSitesResponse is the response of getting all connected sites for a given business
  v1SetInitialKeywordsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The Partner ID of the account to set intital keywords
      businessId:
        type: string
        title: The Business ID of the account to set intital keywords
  v1SetInitialKeywordsResponse:
    type: object
    properties:
      success:
        type: boolean
  v1SetKeywordsRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: The partner ID of the business setting the keywords
      businessId:
        type: string
        title: The account group ID of the business setting the keywords
      keyword:
        type: array
        items:
          type: string
        title: The list of keywords to be tracked
    title: SetKeywordsRequest sets a list of keywords to be tracked using google search console
  v1SetKeywordsResponse:
    type: object
    properties:
      success:
        type: boolean
    title: 'SetKeywordsResponse returns success: true on successful setting of keywords'
  v1SetSiteRequest:
    type: object
    properties:
      partnerId:
        type: string
        title: Partner ID the site is associated with
      businessId:
        type: string
        title: The business ID the site is associated with (aka the account group ID)
      gscSiteUrl:
        type: string
        title: the sites url
      googleUserId:
        type: string
        title: The user's Google ID
    title: The request sent to store a site to start querying data
  v1SetSiteResponse:
    type: object
    properties:
      success:
        type: boolean
    title: The success/fail response when setting a site
