swagger: "2.0"
info:
  title: developer_metrics/v1/api.proto
  version: version not set
tags:
  - name: RepositoriesService
consumes:
  - application/json
produces:
  - application/json
paths:
  /developer_metrics.v1.RepositoriesService/SyncCommitsByRepositoryAndDateRange:
    post:
      summary: SyncCommitsByRepositoryAndDateRange
      operationId: RepositoriesService_SyncCommitsByRepositoryAndDateRange
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SyncByRepositoryAndDateRangeRequest'
      tags:
        - RepositoriesService
  /developer_metrics.v1.RepositoriesService/SyncPullRequestsByRepositoryAndDateRange:
    post:
      summary: SyncPullRequestsByRepositoryAndDateRange
      operationId: RepositoriesService_SyncPullRequestsByRepositoryAndDateRange
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SyncByRepositoryAndDateRangeRequest'
      tags:
        - RepositoriesService
  /developer_metrics.v1.RepositoriesService/SyncPullRequestsCommentsByRepositoryAndDateRange:
    post:
      summary: SyncPullRequestsCommentsByRepositoryAndDateRange
      operationId: RepositoriesService_SyncPullRequestsCommentsByRepositoryAndDateRange
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SyncByRepositoryAndDateRangeRequest'
      tags:
        - RepositoriesService
  /developer_metrics.v1.RepositoriesService/SyncRepositories:
    post:
      summary: Syncs the given repositories with the internal database
      operationId: RepositoriesService_SyncRepositories
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SyncRepositoriesRequest'
      tags:
        - RepositoriesService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Repository:
    type: object
    properties:
      id:
        type: string
        title: The internal id of the repository
    title: A repository
  v1SyncByRepositoryAndDateRangeRequest:
    type: object
    properties:
      repository:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Repository'
        title: The repository to sync
      startDate:
        type: string
        title: The start date of the range to sync
      endDate:
        type: string
        title: The end date of the range to sync
      page:
        type: integer
        format: int32
        title: The page to sync
      pageSize:
        type: integer
        format: int32
        title: The page size to sync
  v1SyncRepositoriesRequest:
    type: object
    properties:
      repositories:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Repository'
        title: The repositories to sync
    title: Request for syncing repositories
