swagger: "2.0"
info:
  title: marketplace_apps/v2/fulfillment_order_config.proto
  version: version not set
tags:
  - name: FulfillmentOrderConfigService
consumes:
  - application/json
produces:
  - application/json
paths:
  /marketplaceapps.v2.FulfillmentOrderConfigService/GetFulfillmentOrderConfig:
    post:
      summary: Get the configuration for a fulfillment order based on application
      operationId: FulfillmentOrderConfigService_GetFulfillmentOrderConfig
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetFulfillmentOrderConfigResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2GetFulfillmentOrderConfigRequest'
      tags:
        - FulfillmentOrderConfigService
  /marketplaceapps.v2.FulfillmentOrderConfigService/UpdateFulfillmentOrderConfig:
    post:
      summary: Updates the draft configuration for fulfillment orders to what is defined.
      operationId: FulfillmentOrderConfigService_UpdateFulfillmentOrderConfig
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2UpdateFulfillmentOrderConfigRequest'
      tags:
        - FulfillmentOrderConfigService
definitions:
  OrderFormFieldOption:
    type: object
    properties:
      label:
        type: string
      value:
        type: string
    title: Stores the valid set of options with display text and internal value. Both fields will always be populated
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1IncludedCommonFormFields:
    type: object
    properties:
      businessName:
        type: boolean
      businessAddress:
        type: boolean
      businessPhoneNumber:
        type: boolean
      businessAccountGroupId:
        type: boolean
      salespersonName:
        type: boolean
      salespersonPhoneNumber:
        type: boolean
      salespersonEmail:
        type: boolean
      contactName:
        type: boolean
      contactPhoneNumber:
        type: boolean
      contactEmail:
        type: boolean
      businessWebsite:
        type: boolean
    title: Common form fields among apps, can be autofilled
  v1OrderForm:
    type: object
    properties:
      orderForm:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1OrderFormField'
        title: 'Order form: fields in the order form'
      commonForm:
        $ref: '#/definitions/v1IncludedCommonFormFields'
        title: 'Order form: common form fields'
      activationMessage:
        type: string
        title: 'Order form: message shown to users upon activating the app'
      separateOrderForms:
        type: boolean
        title: 'Order form: should a multi-activatable app/addon use a separate order form for each activation'
      commonFormRequiredFields:
        $ref: '#/definitions/v1IncludedCommonFormFields'
        title: 'Order form: required common form fields'
      usesPostBillingOrderForm:
        type: boolean
        title: 'Order form: whether or not the order form is to be used post-billing'
      footerText:
        type: string
        title: 'Order form: footer text'
    title: Order form fields
  v1OrderFormField:
    type: object
    properties:
      label:
        type: string
      id:
        type: string
      type:
        type: string
      options:
        type: array
        items:
          type: string
        title: 'Deprecated: Replaced by options_with_labels'
      description:
        type: string
      required:
        type: boolean
      uploadUrl:
        type: string
        title: 'Deprecated: For file upload fields this is where we upload and store the file'
      prefix:
        type: string
        title: For textbox fields, this string will be displayed in front of the textbox
      suffix:
        type: string
        title: For textbox fields, this string will be displayed behind the textbox
      regexValidator:
        type: string
        title: A regex string used to validate a fields answer
      regexErrorMessage:
        type: string
        title: The error message displayed if the regex_validator does not match the answer
      useWebhookValidator:
        type: boolean
        title: Indicates if this field will call out to the order_form_validator_webhook_url under Integration
      allowMultiples:
        type: boolean
        description: |-
          The following 3 options are for dropdowns that allow you to choose multiple options
          Whether or not to allow multiple choices.
      allowDuplicates:
        type: boolean
        description: If you should be able to choose the same option twice.
      maxChoices:
        type: string
        format: int64
        title: The maximum number of choices you can make
      forOfficeUseOnly:
        type: boolean
        title: if this is true the field will not be shown to end users
      optionsWithLabels:
        type: array
        items:
          type: object
          $ref: '#/definitions/OrderFormFieldOption'
      officeEditableOnly:
        type: boolean
        title: if this is true the field will not be editable by end users
    title: Field asking user for information when they try to activate the app
  v2FulfillmentOrderConfig:
    type: object
    properties:
      appId:
        type: string
        title: The Application ID
      release:
        $ref: '#/definitions/v2ReleaseType'
        title: Release State of the Config
      defaultExternalFormUrl:
        type: string
        title: Form to include on the fulfillment order
      isEnabled:
        type: boolean
        title: flag controlling if a config is enabled or not
      fulfillmentForm:
        $ref: '#/definitions/v1OrderForm'
        description: Shared Proto from MarketplaceApp to store a legacy Form Builder config.
      usesFulfillmentForm:
        type: boolean
        description: flag controlling if a Fulfillment Order has a Fulfillment Order Form attached to it when created.
  v2FulfillmentOrderConfigProjectionFilter:
    type: object
    properties:
      includeExternalFormUrl:
        type: boolean
      includeFormConfig:
        type: boolean
  v2GetFulfillmentOrderConfigRequest:
    type: object
    properties:
      appId:
        type: string
      release:
        $ref: '#/definitions/v2ReleaseType'
      projectionFilter:
        $ref: '#/definitions/v2FulfillmentOrderConfigProjectionFilter'
  v2GetFulfillmentOrderConfigResponse:
    type: object
    properties:
      config:
        $ref: '#/definitions/v2FulfillmentOrderConfig'
  v2ReleaseType:
    type: string
    enum:
      - RELEASE_TYPE_DRAFT
      - RELEASE_TYPE_PUBLISHED
    default: RELEASE_TYPE_DRAFT
  v2UpdateFulfillmentOrderConfigRequest:
    type: object
    properties:
      appId:
        type: string
      defaultExternalFormUrl:
        type: string
      isEnabled:
        type: boolean
      fulfillmentForm:
        $ref: '#/definitions/v1OrderForm'
      usesFulfillmentForm:
        type: boolean
